export interface NumberInterpretation {
  title: string;
  keywords: string[];
  shortDesc: string;
  fullText: string;
  famousPeople?: string[];
}

export const lifePathInterpretations: Record<number, NumberInterpretation> = {
  1: {
    title: "The Pioneer",
    keywords: ["Independence", "Leadership", "Innovation", "Courage"],
    shortDesc: "You are a born leader, fiercely independent and driven by the desire to forge your own path.",
    famousPeople: ["Martin Luther King Jr.", "Steve Jobs", "Lady Gaga", "Tom Hanks"],
    fullText: `As a Life Path 1, you carry the energy of the pioneer — the trailblazer who refuses to follow the crowd. You were born with an innate drive to lead, to innovate, and to carve out a path that is uniquely yours. Your soul resonates with the vibration of new beginnings, original ideas, and the raw courage required to stand alone when necessary.

Your greatest strengths lie in your unwavering determination and your ability to see possibilities where others see dead ends. You possess a natural confidence that draws people to you, even when you're not trying. When you walk into a room, your presence commands attention — not through force, but through the sheer magnetism of someone who knows exactly who they are.

However, the shadow side of your Life Path asks you to be mindful of stubbornness and an overly competitive nature. Your fierce independence can sometimes isolate you from the very connections that would enrich your journey. You may struggle with asking for help, viewing it as a sign of weakness rather than wisdom. Learning to lead with compassion — not just conviction — is one of your life's great lessons.

Your life mission is to develop your individuality to its fullest expression and then use that unique perspective to light the way for others. You're not meant to blend in; you're meant to stand out. Whether you find yourself in business, the arts, social justice, or any other field, your purpose is to be the initiator — the one who goes first so others can follow.

The universe placed you on this path because it needs original thinkers who aren't afraid to challenge the status quo. Your journey may feel lonely at times, but remember: every great movement in history began with a single person who dared to think differently. That person is you.`,
  },
  2: {
    title: "The Peacemaker",
    keywords: ["Diplomacy", "Partnership", "Sensitivity", "Harmony"],
    shortDesc: "You are the natural mediator, blessed with profound empathy and the gift of bringing people together.",
    famousPeople: ["Barack Obama", "Madonna", "Emma Watson", "Kanye West"],
    fullText: `As a Life Path 2, you embody the energy of the peacemaker — the gentle diplomat whose greatest power lies in the ability to unite, to heal, and to harmonize opposing forces. Where others might charge forward with brute strength, your approach is subtle, intuitive, and profoundly effective. You understand that true power often comes through patience and partnership.

Your sensitivity is not weakness — it is your superpower. You possess an almost psychic ability to read the emotional currents in any room, sensing tensions that others miss entirely. This makes you an extraordinary friend, partner, and collaborator. People trust you instinctively because you genuinely care about their wellbeing, and they can feel it.

Your greatest strengths include your remarkable patience, your talent for seeing both sides of any conflict, and your ability to create beauty and harmony in your environment. You are naturally artistic and deeply moved by music, art, and the subtler expressions of human creativity. Your presence alone can calm a turbulent situation.

The shadow challenge of your path is learning to stand firm in your own truth rather than constantly adapting to please others. You may find yourself suppressing your own needs to maintain peace, but this approach ultimately leads to resentment and emotional exhaustion. Your lesson is to discover that true harmony includes your own voice — that being a peacemaker doesn't mean being a doormat.

Your life mission revolves around cooperation and partnership. You're here to demonstrate that collaboration creates more powerful outcomes than competition. Whether in love, work, or community, you are the connective tissue that holds everything together. The world needs you precisely because you value connection over conquest.`,
  },
  3: {
    title: "The Creative Spirit",
    keywords: ["Expression", "Joy", "Communication", "Artistry"],
    shortDesc: "You are a radiant creative force, born to inspire others through self-expression, joy, and artistic vision.",
    famousPeople: ["John Travolta", "Celine Dion", "Snoop Dogg", "Hillary Clinton"],
    fullText: `As a Life Path 3, you are the universe's artist — born with an extraordinary gift for self-expression that can manifest through words, images, music, performance, or any creative medium that captures your imagination. Your energy is vibrant, magnetic, and infectious. When you're in your element, you light up entire rooms and inspire everyone around you.

Creativity isn't just something you do — it's who you are. Your mind generates ideas at a pace that can be dizzying even to you. You see beauty in unexpected places, find humor in life's absurdities, and possess a natural charisma that makes you unforgettable. Communication flows through you effortlessly, whether you're telling a story, writing a poem, or simply making someone laugh.

Your greatest strengths are your optimism, your vivid imagination, and your ability to uplift others. You carry a frequency of joy that the world desperately needs. People gravitate toward your warmth and are healed by your laughter. You have a rare gift for making the mundane magical and the painful beautiful.

The shadow side of your path involves scattered energy and a tendency toward superficiality when you're not anchored in a meaningful creative purpose. You may struggle with self-doubt that seems paradoxical given your outward confidence. Emotional sensitivity runs deep beneath your cheerful exterior, and unexpressed feelings can lead to moodiness or escapism.

Your life mission is to use your creative gifts to heal, inspire, and connect. You're not here to be ordinary — you're here to bring color, sound, and wonder into the world. Whether you become a professional artist or simply infuse creativity into everything you touch, your purpose is to remind humanity that joy is not frivolous — it is essential.`,
  },
  4: {
    title: "The Builder",
    keywords: ["Structure", "Discipline", "Stability", "Dedication"],
    shortDesc: "You are the master builder, creating lasting foundations through discipline, patience, and unwavering dedication.",
    famousPeople: ["Oprah Winfrey", "Elton John", "Arnold Schwarzenegger", "Bill Gates"],
    fullText: `As a Life Path 4, you are the builder of the zodiac — the one who turns dreams into reality through sheer determination, methodical planning, and an unshakeable work ethic. While others may dream and drift, you dig in, create structure, and build things that endure. You are the bedrock upon which others can safely build their own aspirations.

Your approach to life is practical, grounded, and deeply honest. You value integrity above all else and have little patience for dishonesty or shortcuts. When you give your word, it is absolute. This reliability makes you one of the most trusted individuals in any circle — people know that when you commit to something, it will be done, and done right.

Your greatest strengths include your exceptional organizational skills, your patience with detailed work, and your ability to see projects through from start to finish. You possess a stamina that others envy — where they burn out or lose interest, you persist. Your logical mind cuts through chaos to find workable solutions.

The shadow challenge of your path is rigidity. Your love of structure can become a prison if you're not careful. You may resist change even when it's necessary, clinging to routines that no longer serve you. Learning flexibility — understanding that sometimes the strongest structures are those that can bend — is your great life lesson.

Your life mission is to create lasting value in the world. Whether you build businesses, homes, systems, or communities, your purpose is to leave behind something tangible and enduring. You're the one who ensures that humanity's greatest ideas don't remain just ideas — you make them real. The world needs your steadiness, your honesty, and your remarkable capacity to turn vision into structure.`,
  },
  5: {
    title: "The Freedom Seeker",
    keywords: ["Adventure", "Change", "Freedom", "Versatility"],
    shortDesc: "You are the eternal adventurer, driven by an insatiable curiosity and a deep need for freedom and experience.",
    famousPeople: ["Angelina Jolie", "Abraham Lincoln", "Beyoncé", "Vincent van Gogh"],
    fullText: `As a Life Path 5, you are the embodiment of freedom — a restless, curious soul who thrives on change, variety, and the intoxicating rush of new experiences. Your life is meant to be a grand adventure, filled with unexpected turns, exotic encounters, and the kind of stories that make others lean in closer. Routine is your kryptonite; the unknown is your playground.

You possess an extraordinary versatility that allows you to adapt to virtually any situation. You're the chameleon of the numerological world — able to reinvent yourself, learn new skills quickly, and connect with people from wildly different backgrounds. Your natural charm and quick wit make you irresistible company, and your enthusiasm for life is genuinely contagious.

Your greatest strengths include your adaptability, your courage in the face of change, and your ability to inspire others to break free from their own limitations. You understand instinctively that life is meant to be lived fully — not observed from the safety of the sidelines. Your progressive thinking often places you ahead of your time.

The shadow side of your path involves excess and irresponsibility. Your hunger for stimulation can lead to overindulgence — whether in substances, relationships, or simply spreading yourself too thin. Commitment can feel like a cage, causing you to flee from the very stability that would help your gifts flourish. Learning that true freedom includes the freedom to commit is your profound life lesson.

Your life mission is to be the bridge between worlds — to gather wisdom through diverse experiences and then share those insights with others. You're here to demonstrate that change is not something to fear but something to embrace. Whether through travel, teaching, entrepreneurship, or social activism, your purpose is to expand the boundaries of what's possible.`,
  },
  6: {
    title: "The Nurturer",
    keywords: ["Responsibility", "Love", "Healing", "Home"],
    shortDesc: "You are the cosmic healer, devoted to love, family, and creating beauty and harmony in all your relationships.",
    famousPeople: ["John Lennon", "Albert Einstein", "Eleanor Roosevelt", "Michael Jackson"],
    fullText: `As a Life Path 6, you carry the vibration of unconditional love — a deep, nurturing energy that makes you the natural caretaker, healer, and protector of those around you. Your heart is vast, your compassion seemingly limitless, and your desire to create harmony in your environment is the driving force of your existence. Home, family, and community are sacred to you.

You possess a remarkable aesthetic sense and an instinctive understanding of beauty in all its forms. Whether you're decorating a home, counseling a friend, or simply arranging flowers, you infuse everything with grace and warmth. People are drawn to your loving presence because with you, they feel safe, valued, and understood in a way that's increasingly rare in our fast-paced world.

Your greatest strengths include your extraordinary capacity for love, your sense of justice, and your ability to take responsibility without resentment. You're the one people call in a crisis because you remain calm, competent, and compassionate when others fall apart. Your devotion to those you love is legendary.

The shadow challenge of your path is martyrdom and codependency. Your desire to help can become controlling if you're not conscious of it. You may sacrifice your own wellbeing for others and then feel bitter when your generosity isn't reciprocated. Learning that you cannot pour from an empty cup — and that sometimes the most loving thing you can do is allow others to struggle and grow — is your essential lesson.

Your life mission is to teach love through example. You're here to create sanctuaries — physical spaces and emotional refuges where people can heal, grow, and feel at home in the world. Whether as a parent, partner, counselor, artist, or community leader, your purpose is to demonstrate that love is not weakness — it is the most powerful force in the universe.`,
  },
  7: {
    title: "The Seeker",
    keywords: ["Wisdom", "Introspection", "Mystery", "Spirituality"],
    shortDesc: "You are the deep thinker, a spiritual seeker driven by an insatiable quest for truth, knowledge, and inner wisdom.",
    famousPeople: ["Princess Diana", "Elon Musk", "Leonardo DiCaprio", "Stephen Hawking"],
    fullText: `As a Life Path 7, you are the mystic philosopher of the numerological realm — a deep, introspective soul who is driven by an unquenchable thirst for truth, meaning, and understanding. While others are content with surface-level explanations, you must go deeper. You need to understand the why behind the what, the invisible forces that shape visible reality.

Your mind is extraordinary — analytical yet intuitive, scientific yet spiritual. You possess the rare ability to hold seemingly contradictory truths simultaneously, understanding that reality is far more nuanced and mysterious than most people acknowledge. You are equally comfortable in a laboratory and a meditation retreat, because for you, both are pathways to the same ultimate truth.

Your greatest strengths include your penetrating intellect, your powerful intuition, and your ability to see through deception and pretense with remarkable clarity. You're a natural researcher, analyst, and truth-seeker. When you focus your considerable mental powers on a question, you often arrive at insights that astound those around you.

The shadow challenge of your path is isolation and cynicism. Your need for solitude can become excessive, cutting you off from the human connections that actually nourish your spiritual growth. You may struggle with trust, maintaining emotional walls that protect you but also prevent intimacy. Perfectionism can paralyze you, as your high standards make everything seem inadequate.

Your life mission is to bridge the gap between the seen and unseen worlds — to bring spiritual wisdom into practical reality. You're not here to be a hermit, despite the appeal. You're here to dive deep into the mysteries of existence and then surface with pearls of insight that can illuminate the path for others. The world needs your wisdom, your discernment, and your courage to ask the questions that everyone else is afraid to ask.`,
  },
  8: {
    title: "The Powerhouse",
    keywords: ["Authority", "Abundance", "Achievement", "Material Mastery"],
    shortDesc: "You are the manifestation master, destined for material success, authority, and transformative leadership.",
    famousPeople: ["Nelson Mandela", "Pablo Picasso", "Sandra Bullock", "50 Cent"],
    fullText: `As a Life Path 8, you are the powerhouse — a force of nature who is destined to master the material world and wield authority with wisdom. You carry the vibration of abundance, achievement, and executive leadership. The universe didn't design you to play small; you are built for big stages, big decisions, and big impact.

Your relationship with power and money is central to your life's journey. Unlike other Life Paths, you're not meant to transcend material concerns — you're meant to master them. You possess an innate business acumen, a strategic mind, and the kind of relentless drive that can move mountains. When you set your sights on a goal, the universe itself seems to conspire to help you achieve it.

Your greatest strengths include your exceptional judgment, your ability to organize large-scale operations, and your talent for turning vision into profitable reality. You command respect naturally because people sense your competence and authority. You understand power dynamics instinctively and know how to navigate complex hierarchical structures.

The shadow challenge of your path involves the misuse of power and a tendency toward workaholism. You may become so focused on achievement that you neglect relationships, health, and spiritual growth. Material success can become an obsession rather than a tool, and you might measure your worth solely by your bank account. Learning that true abundance encompasses all areas of life is your critical lesson.

Your life mission is to demonstrate that material success and spiritual integrity are not mutually exclusive. You're here to build empires — but empires that serve humanity, that create opportunities for others, and that prove that power wielded with wisdom is a force for tremendous good. The world needs your strength, your vision, and your ability to make things happen on a grand scale.`,
  },
  9: {
    title: "The Humanitarian",
    keywords: ["Compassion", "Wisdom", "Completion", "Universal Love"],
    shortDesc: "You are the old soul, a compassionate humanitarian driven by universal love and a mission to serve the greater good.",
    famousPeople: ["Mahatma Gandhi", "Mother Teresa", "Jimi Hendrix", "Morgan Freeman"],
    fullText: `As a Life Path 9, you are the old soul of the numerological world — a wise, compassionate being who carries the accumulated wisdom of all the numbers that came before you. You vibrate at the highest single-digit frequency, and your journey is fundamentally about completion, release, and selfless service to humanity. You are here to love not just individuals, but the world itself.

Your perspective is remarkably broad. While others focus on personal concerns, you naturally see the bigger picture — the interconnectedness of all things, the patterns that connect seemingly unrelated events, and the underlying unity beneath surface-level divisions. This gives you a wisdom and tolerance that can seem almost otherworldly.

Your greatest strengths include your profound compassion, your creative vision, and your ability to inspire others toward their highest potential. You possess a natural magnetism that draws people from all walks of life. Artists, healers, teachers, and visionaries are often found among Life Path 9s, because your soul is driven to contribute something meaningful to the collective human experience.

The shadow challenge of your path involves letting go. Despite being the number of completion, you may struggle fiercely with release — clinging to relationships, identities, and situations long past their expiration date. You may also struggle with feelings of superiority or become disillusioned when the world doesn't live up to your idealistic vision. Learning that endings are sacred — that they create space for new beginnings — is your most important lesson.

Your life mission is nothing less than the elevation of human consciousness. You're here to teach compassion by living it, to heal by being a channel for universal love, and to create art and ideas that remind humanity of its highest nature. The world needs your wisdom, your generosity, and your unwavering belief that a better world is possible.`,
  },
  11: {
    title: "The Illuminator",
    keywords: ["Intuition", "Inspiration", "Spiritual Messenger", "Visionary"],
    shortDesc: "You are a Master Number — a spiritual messenger and visionary whose heightened intuition can illuminate the world.",
    famousPeople: ["Michelle Obama", "Wolfgang Mozart", "David Beckham", "Edgar Allan Poe"],
    fullText: `As a Life Path 11, you carry one of the rare Master Numbers — a double dose of spiritual energy that marks you as a messenger, visionary, and illuminator. You walk between worlds, serving as a bridge between the mundane and the mystical. Your intuition is not ordinary; it borders on the prophetic, offering you glimpses of truths that most people never access.

This is both your gift and your burden. The intensity of the 11 vibration can feel overwhelming, especially in your younger years. You may experience extreme sensitivity to environments and emotions, vivid dreams, and a persistent feeling that you're here for something significant — even before you understand what that something is. You are an antenna for cosmic energy, constantly receiving signals from a frequency most people can't even detect.

Your greatest strengths include your extraordinary intuition, your ability to inspire and uplift others through your mere presence, and your visionary thinking that often proves prophetic. You possess a charisma that's deeply spiritual in nature — people are drawn to your light because it awakens something dormant within them.

The shadow challenge of your Master Number involves nervous tension and self-doubt. The gap between your spiritual potential and your human reality can create intense anxiety. You may oscillate between grandiosity and crippling insecurity. Without proper grounding practices, the 11 energy can manifest as anxiety disorders, phobias, or paralysis in the face of your own potential.

Your life mission is to be a spiritual lighthouse — to channel divine inspiration into forms that can uplift and awaken others. Whether through art, teaching, healing, or leadership, you are here to demonstrate that the invisible world is just as real as the visible one. Your path is not easy, but it is profoundly meaningful. The world needs your light, your vision, and your courage to speak truths that others only sense in their dreams.`,
  },
  22: {
    title: "The Master Builder",
    keywords: ["Mastery", "Vision", "Legacy", "Transformation"],
    shortDesc: "You carry the most powerful Master Number — destined to build something of lasting significance for all humanity.",
    famousPeople: ["Paul McCartney", "the Dalai Lama", "Will Smith", "Richard Branson"],
    fullText: `As a Life Path 22, you carry the most powerful vibration in all of numerology — the Master Builder. This is not merely a number; it is a calling of extraordinary magnitude. You possess the rare combination of visionary dreams (from the 11) and practical mastery (from the 4), giving you the potential to turn the most ambitious visions into concrete reality. You are here to build something that outlasts you.

The scope of your potential is staggering. While others think in terms of personal success, you instinctively think in terms of legacy — structures, systems, and institutions that serve humanity across generations. This isn't grandiosity; it's the natural expression of the 22 vibration. You have been given the tools, the vision, and the stamina to create on a scale that most people can barely imagine.

Your greatest strengths include your unparalleled ability to organize large-scale projects, your visionary thinking combined with practical execution, and your natural authority that inspires teams to achieve the seemingly impossible. You possess both the blueprint and the building skills, making you uniquely capable of manifesting grand visions.

The shadow challenge of your Master Number is the immense pressure you place on yourself. The weight of your potential can become crushing if you interpret it as obligation rather than invitation. You may struggle with feelings of inadequacy, constantly measuring yourself against an impossible ideal. Burnout is a real risk, as your drive to build can consume everything else in your life.

Your life mission is to leave a lasting legacy — to build bridges (literal or metaphorical) that connect people, ideas, and possibilities in ways that transform the world. You're not here for quick wins or personal glory. You're here to create something so significant that it continues to serve humanity long after you're gone. The world needs your vision, your discipline, and your extraordinary capacity to turn dreams into foundations.`,
  },
  33: {
    title: "The Master Healer",
    keywords: ["Unconditional Love", "Spiritual Teaching", "Healing", "Devotion"],
    shortDesc: "You are the rarest Master Number — a master teacher and healer devoted to uplifting humanity through selfless love.",
    famousPeople: ["Albert Einstein (by some calculations)", "Meryl Streep", "Francis of Assisi"],
    fullText: `As a Life Path 33, you embody the rarest and most elevated vibration in numerology — the Master Healer and Teacher. This number combines the intuitive illumination of the 11 with the master building capabilities of the 22, producing a being whose purpose is nothing less than the spiritual upliftment of humanity through unconditional love, healing, and selfless devotion.

You are a walking embodiment of compassion. Your capacity to love is so vast that it can seem almost inhuman in its scope and intensity. You don't just feel for individuals — you feel for humanity itself. This profound empathy, when channeled properly, gives you the ability to heal at the deepest levels, touching wounds that others cannot even see.

Your greatest strengths include your extraordinary healing presence, your ability to inspire spiritual growth in others simply by being yourself, and your devotion to service that goes far beyond ordinary helpfulness. You possess a wisdom that seems to come from lifetimes of experience, and people instinctively seek your counsel in their darkest hours.

The shadow challenge of your Master Number is the enormous sacrifice it demands. Living at the 33 vibration requires a level of selflessness that can be depleting if you don't maintain strong boundaries and self-care practices. You may attract codependent relationships or lose yourself in others' pain. The key lesson is that you cannot heal the world if you neglect your own healing.

Your life mission is to be a master teacher of love — to demonstrate through your life that unconditional love is not just a concept but a living, breathing force that can transform everything it touches. Whether through formal teaching, healing arts, spiritual guidance, or simply living as an example, your purpose is to raise the vibration of every person and place you encounter.`,
  },
};

export const expressionInterpretations: Record<number, NumberInterpretation> = {
  1: { title: "The Original Thinker", keywords: ["Innovation", "Self-reliance", "Ambition"], shortDesc: "Your name reveals a destiny of original thought and independent achievement. You are meant to pioneer new ideas and lead with unwavering conviction.", fullText: `Your Expression Number 1 reveals that your name carries the vibration of the innovator and the individualist. This isn't just about personality — it's about the talents and abilities encoded into your very identity from birth. The universe chose your name carefully, embedding within it the seed of original thinking and self-directed achievement.\n\nYour destiny is to develop complete self-reliance and to lead by example. You possess latent talents for entrepreneurship, creative problem-solving, and inspiring others through the courage of your convictions. The world perceives you as someone with tremendous potential for groundbreaking achievement — and they're right.\n\nTo fulfill your Expression Number, you must learn to trust your own ideas even when they contradict popular opinion. Your path is to develop the courage to stand alone if necessary, to initiate rather than follow, and to turn your original visions into tangible realities. The more you lean into your natural leadership abilities, the more aligned you become with your true destiny.` },
  2: { title: "The Harmonizer", keywords: ["Cooperation", "Intuition", "Sensitivity"], shortDesc: "Your name encodes a destiny of partnership and diplomacy. You are meant to bring people together and create harmony through understanding.", fullText: `Your Expression Number 2 reveals a destiny rooted in cooperation, partnership, and the subtle art of diplomacy. Your name vibrates with the energy of the peacemaker and the mediator — someone whose greatest talents emerge not in solo performance but in the beautiful dance of collaboration.\n\nThe talents encoded in your name include extraordinary emotional intelligence, a gift for reading between the lines, and an ability to create consensus where others see only conflict. You are the glue that holds teams, families, and communities together. Your sensitivity to nuance and detail makes you exceptional at any work requiring precision and care.\n\nTo fully express this vibration, you must embrace your receptive nature as a strength rather than viewing it as passivity. Your destiny is fulfilled through supportive roles that amplify others while quietly weaving the threads that hold everything together. The world needs your patience, your perception, and your profound understanding of human connection.` },
  3: { title: "The Communicator", keywords: ["Creativity", "Expression", "Joy"], shortDesc: "Your name vibrates with creative expression and charisma. You are destined to inspire and uplift through the power of your words and artistic vision.", fullText: `Your Expression Number 3 reveals a destiny blazing with creative fire. Your name is a vessel for artistic expression, communication, and the kind of infectious joy that can transform the emotional atmosphere of any space you enter. The universe embedded within your name an extraordinary gift for turning thoughts and feelings into forms that others can experience and enjoy.\n\nYour talents include writing, speaking, performing, and any form of creative expression. You have a natural charisma that makes people want to listen, and a way with words that can move hearts and change minds. Humor comes naturally to you, and you instinctively understand that laughter is one of life's most powerful medicines.\n\nTo fulfill your Expression Number, you must resist the temptation to scatter your creative energy across too many projects. Your destiny is to choose your medium and develop true mastery within it. When you focus your considerable creative power, the results are nothing short of magical.` },
  4: { title: "The Organizer", keywords: ["Structure", "Reliability", "Hard Work"], shortDesc: "Your name carries the vibration of the master organizer. You are destined to create enduring structures that serve the practical needs of the world.", fullText: `Your Expression Number 4 reveals a destiny centered on building, organizing, and creating systems that work. Your name vibrates with the energy of reliability, hard work, and the kind of practical wisdom that turns chaos into order. You are the one the universe calls when something needs to be built right the first time.\n\nYour talents include exceptional organizational ability, attention to detail, and a work ethic that puts most others to shame. You possess an instinctive understanding of how things fit together — whether physical structures, business systems, or community organizations. People trust you because your word is your bond.\n\nTo fulfill this destiny, embrace your role as the foundation-builder. Your path is not glamorous, but it is profoundly important. Every great achievement in human history rests on the kind of solid foundation that people like you create. The world needs your steadiness, your integrity, and your unwavering commitment to doing things properly.` },
  5: { title: "The Adventurer", keywords: ["Freedom", "Versatility", "Change"], shortDesc: "Your name encodes the energy of freedom and versatile experience. You are destined to be a bridge between different worlds and ways of thinking.", fullText: `Your Expression Number 5 reveals a destiny filled with change, travel, and the kind of diverse experience that transforms a person into a true citizen of the world. Your name vibrates with the energy of freedom, adaptability, and an insatiable curiosity about everything life has to offer.\n\nYour talents include quick learning, extraordinary adaptability, and the ability to communicate with people from all backgrounds. You possess a magnetic personality that makes you effective in sales, promotion, media, and any field that requires thinking on your feet. Your versatility is remarkable — you can reinvent yourself more successfully than almost anyone.\n\nTo fulfill your Expression Number, you must learn to channel your love of freedom into constructive paths rather than mere restlessness. Your destiny involves gathering wisdom through diverse experiences and then sharing those insights with others, serving as a bridge between different cultures, ideas, and perspectives.` },
  6: { title: "The Caretaker", keywords: ["Service", "Beauty", "Responsibility"], shortDesc: "Your name carries the vibration of love, service, and aesthetic beauty. You are destined to nurture and heal through your devotion to others.", fullText: `Your Expression Number 6 reveals a destiny woven with threads of love, responsibility, and aesthetic beauty. Your name resonates with the energy of the cosmic caretaker — someone whose greatest fulfillment comes through service to family, community, and ideals of beauty and harmony.\n\nYour talents include counseling, healing, teaching, and any work involving domestic arts and beauty. You have an extraordinary aesthetic sense and can create harmony in physical spaces, relationships, and communities. Your advice is sought because it comes from genuine wisdom born of deep empathy.\n\nTo fulfill this vibration, you must learn to balance giving with receiving. Your destiny involves creating environments of beauty and safety where others can heal and grow — but not at the expense of your own wellbeing. The world needs your nurturing presence, but it needs you whole and healthy.` },
  7: { title: "The Analyst", keywords: ["Wisdom", "Research", "Spirituality"], shortDesc: "Your name vibrates with the energy of deep analysis and spiritual seeking. You are destined to uncover truths hidden from ordinary perception.", fullText: `Your Expression Number 7 reveals a destiny devoted to the pursuit of truth, wisdom, and understanding at the deepest levels. Your name carries the vibration of the spiritual seeker and analytical mind — someone whose purpose involves peeling back layers of reality to discover what lies beneath.\n\nYour talents include research, analysis, technical expertise, and spiritual insight. You possess a mind that naturally goes deeper than surface appearances, making you brilliant at investigation, scientific inquiry, and philosophical contemplation. Your intuition is remarkably accurate when you learn to trust it.\n\nTo fulfill this destiny, you must honor both your need for solitude and your responsibility to share your insights. Your path is to become a vessel for wisdom — gathering it through study, meditation, and experience, then distilling it into forms that others can access and benefit from.` },
  8: { title: "The Executive", keywords: ["Power", "Achievement", "Material Mastery"], shortDesc: "Your name resonates with the energy of authority and material achievement. You are destined for positions of power and significant financial success.", fullText: `Your Expression Number 8 reveals a destiny of power, authority, and material achievement on a significant scale. Your name vibrates with executive energy — the kind of natural command that positions you for leadership roles where important decisions are made and substantial resources are managed.\n\nYour talents include business acumen, strategic thinking, and an instinctive understanding of money and power dynamics. You possess natural authority that others recognize and respect. You're skilled at seeing the big picture while simultaneously managing the details that make large-scale achievements possible.\n\nTo fulfill this destiny, you must learn to wield power with wisdom and generosity. Your path involves achieving material mastery not as an end in itself, but as a means of creating positive change in the world. The universe has given you the tools for extraordinary achievement — the question is whether you'll use them for personal gain alone or for the greater good.` },
  9: { title: "The Philanthropist", keywords: ["Compassion", "Global Vision", "Completion"], shortDesc: "Your name carries the highest single-digit vibration — a destiny of universal service, artistic mastery, and humanitarian achievement.", fullText: `Your Expression Number 9 reveals a destiny that encompasses the broadest possible scope of human experience. Your name resonates with the energy of the humanitarian, the artist, and the wise counselor whose vision extends far beyond personal concerns to embrace the wellbeing of all.\n\nYour talents include artistic expression, compassionate leadership, and the ability to inspire others toward their highest potential. You possess a natural wisdom that comes from seeing the interconnectedness of all things. Your creative abilities are significant, and your work often carries a message of universal truth.\n\nTo fulfill this vibration, you must learn the art of letting go — releasing attachment to outcomes while maintaining passionate engagement with the process. Your destiny involves completion and transformation — ending cycles, releasing what no longer serves, and making space for new beginnings. The world needs your broad vision and generous heart.` },
  11: { title: "The Visionary Messenger", keywords: ["Inspiration", "Revelation", "Channeling"], shortDesc: "Your name carries a Master vibration of spiritual inspiration. You are destined to receive and transmit visionary insights that can transform collective consciousness.", fullText: `Your Expression Number 11 reveals a Master Number destiny of extraordinary spiritual significance. Your name vibrates at a frequency that enables you to serve as a channel for divine inspiration — receiving insights from higher dimensions and translating them into forms that ordinary consciousness can comprehend.\n\nYour talents include visionary thinking, inspirational communication, and the ability to catalyze spiritual awakening in others. You possess an intuitive sensitivity that borders on the clairvoyant, often knowing things before they happen or understanding people at levels that seem almost supernatural.\n\nTo fulfill this Master Number destiny, you must develop the courage to share your visions even when they seem impractical or strange to others. Your path requires balancing the ethereal 11 energy with the practical grounding of the 2. The world needs your spiritual insights, but they must be communicated in accessible, practical ways to create real impact.` },
  22: { title: "The Architect of Destiny", keywords: ["Grand Vision", "Practical Mastery", "World Impact"], shortDesc: "Your name holds the Master Builder vibration — the highest potential for manifesting visionary ideas into physical reality on a global scale.", fullText: `Your Expression Number 22 marks you as carrying perhaps the most powerful vibration in all of numerology. Your name resonates with the Master Builder frequency — combining the spiritual illumination of 11 with the practical mastery of 4 to create an individual capable of manifesting grand visions on a scale that impacts the world.\n\nYour talents include visionary planning, organizational genius, and the ability to inspire large groups of people to work toward seemingly impossible goals. You see potential where others see limitations, and you possess the practical skills to turn those possibilities into concrete realities.\n\nTo fulfill this extraordinary destiny, you must resist the temptation to play small. Your path is one of monumental achievement — not for ego, but for service. The universe has equipped you with tools that most people can barely comprehend. Your responsibility is to use them wisely, building structures and systems that serve not just this generation, but generations to come.` },
  33: { title: "The Master Teacher of Love", keywords: ["Selfless Service", "Cosmic Love", "Spiritual Mastery"], shortDesc: "Your name vibrates at the highest Master Number — a rare destiny of spiritual mastery through the ultimate expression of unconditional love.", fullText: `Your Expression Number 33 represents the pinnacle of numerological vibration — the Master Teacher whose very name encodes the potential for profound spiritual mastery. This is the number of the cosmic healer, the selfless servant, and the enlightened teacher whose love is so vast and unconditional that it transcends personal attachment.\n\nYour talents include healing at the deepest levels, teaching through example, and holding space for others' transformation with patience and compassion that seem almost superhuman. Your presence alone can shift the energy of a room, calming anxiety and awakening hope.\n\nTo fulfill this rare destiny, you must embrace your role as a beacon of unconditional love while maintaining strong personal boundaries. Your path demands extraordinary selflessness, but not self-abandonment. The world needs your healing presence, your wise counsel, and your unwavering demonstration that love — pure, unconditional love — is the most powerful force in existence.` },
};

export const soulUrgeInterpretations: Record<number, NumberInterpretation> = {
  1: { title: "The Independent Heart", keywords: ["Autonomy", "Self-direction", "Originality"], shortDesc: "Deep inside, you crave complete independence and the freedom to follow your own unique path without compromise.", fullText: `Your Soul Urge Number 1 reveals that beneath everything you show the world, your deepest desire is for independence, originality, and the freedom to be completely, authentically yourself. This isn't mere preference — it's a soul-level need that drives everything you do, whether you're consciously aware of it or not.\n\nYou feel most fulfilled when you're pioneering something new, leading by your own vision, and proving that your unique approach has value. There is a fire inside you that resists being told what to do or how to think. Your soul craves the experience of standing alone in your truth, even when it's uncomfortable or unpopular.\n\nThis inner drive makes you restless in environments where conformity is expected. Your relationships work best when your partner respects your need for independence rather than interpreting it as a lack of love. Understanding this deep motivation can transform your life — once you stop apologizing for your need to be an individual and start honoring it as the sacred impulse it truly is.` },
  2: { title: "The Loving Heart", keywords: ["Connection", "Peace", "Partnership"], shortDesc: "Your deepest desire is for love, partnership, and the kind of profound emotional connection that makes you feel truly seen and understood.", fullText: `Your Soul Urge Number 2 reveals that your innermost desire — the secret engine driving all your choices — is the longing for deep, authentic connection. More than success, more than recognition, more than adventure, what your soul craves is to love and be loved in a way that feels truly reciprocal and genuine.\n\nYou feel most alive in moments of authentic intimacy — whether with a romantic partner, a close friend, or a trusted collaborator. Harmony in your environment isn't a luxury for you; it's a necessity. Discord and conflict affect you at a cellular level, disrupting your ability to think, create, and function at your best.\n\nThis soul desire makes you extraordinarily attuned to the emotional needs of others. Your sensitivity is your gift, but it also makes you vulnerable to losing yourself in relationships. The key to fulfilling your Soul Urge is learning that the deepest connection begins with connection to yourself — that you must know and love who you are before you can truly merge with another.` },
  3: { title: "The Joyful Heart", keywords: ["Self-expression", "Creativity", "Recognition"], shortDesc: "At your core, you long to express yourself fully and to be appreciated for your unique creative gifts and joyful spirit.", fullText: `Your Soul Urge Number 3 reveals that your deepest motivation is the need for creative self-expression and the joy of being truly seen and appreciated for your unique gifts. Your soul doesn't just want to create — it needs to create the way lungs need to breathe. Without an outlet for your considerable creative energy, you feel suffocated and diminished.\n\nYou are most fulfilled when sharing your vision with an appreciative audience, whether that's one person or one million. Recognition matters to you not because you're vain, but because it confirms that your inner world has value — that the beauty you perceive and create resonates with others.\n\nThis soul urge drives you toward artistic, communicative, and performative endeavors. Understanding this motivation helps explain why you may feel inexplicably depressed during periods when your creative expression is stifled. Honor this inner need by making space for creativity in your daily life — it's not a hobby, it's a soul requirement.` },
  4: { title: "The Grounded Heart", keywords: ["Security", "Order", "Achievement"], shortDesc: "Deep within, you crave stability, order, and the satisfaction of building something lasting and meaningful through dedicated effort.", fullText: `Your Soul Urge Number 4 reveals that at the deepest level, your soul seeks security, stability, and the profound satisfaction that comes from building something of enduring value. While others might crave excitement or recognition, your inner world is oriented toward creating order from chaos and establishing foundations that will stand the test of time.\n\nYou feel most fulfilled when you have a clear plan, a solid routine, and tangible evidence that your efforts are producing lasting results. There's a craftsman quality to your inner nature — you derive deep satisfaction from doing things properly, from mastering skills, and from seeing your work stand up to scrutiny.\n\nThis soul urge makes you crave predictability in ways that others might not understand. Uncertainty and chaos genuinely disturb your inner peace. Understanding this motivation helps you choose careers, relationships, and lifestyles that honor your need for structure while still allowing room for growth.` },
  5: { title: "The Free Heart", keywords: ["Freedom", "Experience", "Stimulation"], shortDesc: "Your soul burns with an insatiable desire for freedom, variety, and the thrill of experiencing everything life has to offer.", fullText: `Your Soul Urge Number 5 reveals that your innermost desire is freedom in its purest form — freedom to explore, to experience, to change, and to live life on your own terms without restriction or monotony. This is a powerful, sometimes overwhelming drive that colors every aspect of your inner world.\n\nYou feel most alive when you're experiencing something new — a new place, a new idea, a new person, a new sensation. Routine is physically painful for your soul. You need variety the way others need stability, and without it, you feel like a caged bird whose very nature is being violated.\n\nThis soul urge explains your restlessness, your difficulty with long-term commitments, and your tendency to feel claustrophobic in situations that others find perfectly comfortable. The key to working with this energy is learning that true freedom isn't about running away from things — it's about having the courage to run toward your deepest truth.` },
  6: { title: "The Devoted Heart", keywords: ["Love", "Family", "Beauty"], shortDesc: "Your soul's deepest yearning is to love completely, to nurture those you care for, and to create a life filled with beauty and harmony.", fullText: `Your Soul Urge Number 6 reveals that your innermost desire revolves around love, family, and the creation of beauty and harmony in every aspect of your life. More than anything else, your soul longs to love and be loved — to create a sanctuary where the people you care about can feel safe, valued, and nourished.\n\nYou feel most fulfilled when your home life is peaceful, your relationships are thriving, and your environment reflects the beauty you carry inside. Aesthetic harmony isn't superficial for you — it's a reflection of the inner harmony your soul craves. You are genuinely distressed by ugliness, discord, and injustice.\n\nThis soul urge drives you toward caretaking roles and can sometimes lead to over-giving. Understanding this motivation helps you recognize when your desire to help has crossed into codependency. Your challenge is to extend the same loving devotion to yourself that you so naturally offer to others.` },
  7: { title: "The Seeking Heart", keywords: ["Truth", "Solitude", "Understanding"], shortDesc: "Deep within, your soul craves spiritual understanding, peaceful solitude, and the revelation of life's hidden truths.", fullText: `Your Soul Urge Number 7 reveals that your deepest motivation is the quest for truth and spiritual understanding. While others might be driven by love, money, or adventure, your soul hungers for something more elusive — genuine wisdom, authentic understanding of life's mysteries, and the peace that comes from knowing rather than merely believing.\n\nYou feel most fulfilled in moments of quiet contemplation, deep study, or spiritual practice. Solitude is not lonely for you — it's luxurious. It's in silence that you hear the answers to questions most people haven't even thought to ask. Your inner world is rich, complex, and far more important to you than outward appearances.\n\nThis soul urge explains your need for privacy, your discomfort with small talk, and your tendency to withdraw from social situations that feel superficial. Understanding this drive helps you structure your life in ways that honor your need for depth while maintaining the human connections that, whether you admit it or not, are also essential to your growth.` },
  8: { title: "The Ambitious Heart", keywords: ["Power", "Success", "Recognition"], shortDesc: "Your soul is driven by a powerful desire for achievement, authority, and the kind of success that commands respect and creates lasting impact.", fullText: `Your Soul Urge Number 8 reveals that your deepest inner drive is toward power, achievement, and material mastery. This isn't shallow ambition — it's a soul-level understanding that you are meant to operate at the highest levels, making decisions that matter and managing resources that create real-world impact.\n\nYou feel most fulfilled when you're in a position of authority, when your efforts produce tangible results, and when you can see the concrete evidence of your success. Financial security isn't just about comfort for you — it represents freedom, influence, and the ability to make things happen on a scale that matches your inner vision.\n\nThis soul urge drives you toward leadership and can sometimes create conflict in relationships when your drive for achievement overshadows your emotional connections. Understanding this motivation helps you pursue success in ways that don't sacrifice the personal relationships that, deep down, you value just as much as your worldly accomplishments.` },
  9: { title: "The Compassionate Heart", keywords: ["Service", "Compassion", "Universal Love"], shortDesc: "Your soul yearns to serve humanity, to give selflessly, and to contribute something meaningful to the healing and evolution of the world.", fullText: `Your Soul Urge Number 9 reveals that your deepest desire is to serve something greater than yourself — to give, to heal, and to contribute to the wellbeing of the world in ways that transcend personal benefit. Your soul operates on a universal frequency, feeling the joy and pain of humanity as if it were your own.\n\nYou feel most fulfilled when you're making a difference — whether through charitable work, artistic creation, teaching, healing, or simply being a compassionate presence in the lives of those who are suffering. Material pursuits feel empty to you unless they're connected to a larger purpose.\n\nThis soul urge explains your idealism, your generous nature, and sometimes your frustration with a world that doesn't match your vision of what it could be. Understanding this drive helps you channel your compassion effectively rather than burning out from trying to save everyone. Your challenge is to serve without losing yourself in the process.` },
  11: { title: "The Inspired Heart", keywords: ["Revelation", "Spiritual Connection", "Higher Purpose"], shortDesc: "Your soul craves transcendent spiritual experience and the ability to channel divine inspiration into forms that uplift and transform others.", fullText: `Your Soul Urge Master Number 11 reveals an inner world of extraordinary depth and spiritual intensity. Your deepest desire is to experience direct connection with higher consciousness and to serve as a conduit for inspiration that can uplift and transform those around you.\n\nYou feel most fulfilled in moments of spiritual clarity — when the veil thins and you glimpse the deeper reality beneath ordinary appearances. These experiences are not fantasy for you; they're the most real moments of your life. Your soul aches for meaning that transcends the mundane, for beauty that touches the eternal.\n\nThis powerful inner drive can create tension in everyday life, where practical demands feel trivial compared to the spiritual magnificence you've touched. Your challenge is to bring heaven down to earth — to live your spiritual vision in practical, grounded ways that serve both your own growth and the awakening of others.` },
  22: { title: "The Visionary Heart", keywords: ["Grand Purpose", "World-building", "Legacy"], shortDesc: "Your soul is driven by an immense desire to build something of monumental significance that transforms the world for the better.", fullText: `Your Soul Urge Master Number 22 reveals an inner motivation of staggering scope — your deepest desire is to create something of lasting, world-changing significance. This isn't ordinary ambition; it's a soul-level calling to build, transform, and leave a legacy that serves humanity for generations.\n\nYou feel most alive when working on large-scale projects that match the enormity of your inner vision. Small thinking suffocates your soul. You need goals that challenge the very limits of what's considered possible, and you possess the inner resources to achieve them.\n\nThis master soul urge can create intense inner pressure, as the gap between your vision and current reality may sometimes feel overwhelming. Understanding this drive helps you pace yourself, build systematically, and trust that the universe has given you both the vision and the capacity to manifest it — one solid step at a time.` },
  33: { title: "The Healer's Heart", keywords: ["Unconditional Love", "Healing", "Sacrifice"], shortDesc: "Your soul's deepest yearning is to love unconditionally and to heal at the most profound level — serving as a living embodiment of compassion.", fullText: `Your Soul Urge Master Number 33 reveals the deepest possible motivation — a drive toward unconditional love and selfless service so powerful that it transcends ordinary human experience. Your soul yearns to heal, to teach, and to embody love in its purest, most transformative form.\n\nYou feel most fulfilled when you're serving others at the deepest level — not with conditions or expectations, but with the kind of pure compassion that transforms pain into purpose and suffering into wisdom.\n\nThis extraordinary soul urge demands extraordinary self-care. Your challenge is to maintain the purity of your loving intention while establishing boundaries that prevent you from being consumed by the needs of others. The world desperately needs your healing presence, but only if you remain whole enough to offer it.` },
};

export const personalityInterpretations: Record<number, NumberInterpretation> = {
  1: { title: "The Commanding Presence", keywords: ["Strong", "Confident", "Direct"], shortDesc: "Others perceive you as a natural leader — someone with confidence, ambition, and the assertiveness to make things happen.", fullText: `Your Personality Number 1 shapes how the world sees you before they truly know you. You project an aura of confidence, competence, and self-assurance that commands immediate attention. People perceive you as someone who knows what they want and isn't afraid to go after it.\n\nYour first impression is one of strength and independence. Others may see you as ambitious, driven, and perhaps a bit intimidating. Your energy communicates 'I can handle this' — making people naturally defer to your leadership, even in situations where you haven't specifically sought it.\n\nThis persona serves you well in professional settings and new social situations, but be aware that it can sometimes create distance. People may assume you don't need help or emotional support, when in reality, everyone does. Learning to show vulnerability selectively can deepen your connections without sacrificing the respect your strong presence commands.` },
  2: { title: "The Gentle Presence", keywords: ["Approachable", "Warm", "Tactful"], shortDesc: "Others see you as warm, approachable, and naturally diplomatic — someone who makes everyone feel comfortable and heard.", fullText: `Your Personality Number 2 creates a first impression of warmth, approachability, and refined sensitivity. People perceive you as someone who genuinely listens, who cares about their feelings, and who radiates a quiet kind of grace that puts others at ease.\n\nYour outward energy says 'I'm here for you' in a way that draws people to confide in you quickly, sometimes sharing more than they intended. You project an air of diplomacy and tact that makes you a natural fit for collaborative environments. Your appearance tends to be neat, tasteful, and harmonious.\n\nThis gentle persona is a tremendous asset in relationships and partnership-oriented careers, but be mindful that some may mistake your softness for weakness. Building in moments where you display your inner steel reminds others that kindness and strength are not mutually exclusive.` },
  3: { title: "The Charismatic Presence", keywords: ["Charming", "Expressive", "Entertaining"], shortDesc: "The world sees you as a charismatic, expressive, and entertaining personality — someone whose charm and wit light up every room.", fullText: `Your Personality Number 3 projects an irresistibly charming, expressive, and vibrant energy. When you enter a room, people notice — not because you're loud, but because your natural charisma creates a gravitational pull. Others see you as witty, creative, and genuinely fun to be around.\n\nYour first impression radiates optimism and social ease. People perceive you as someone who can hold court in any conversation, who finds humor in life's challenges, and whose company makes everything more enjoyable. You tend to dress with flair and express yourself with natural dramatic timing.\n\nThis magnetic persona opens many doors for you socially and professionally. However, be aware that others may not always take you seriously, assuming that someone so entertaining must be lightweight. When you need to convey depth and gravitas, consciously modulating your natural expressiveness can help others see the substance beneath the sparkle.` },
  4: { title: "The Reliable Presence", keywords: ["Dependable", "Practical", "Organized"], shortDesc: "Others perceive you as solid, dependable, and organized — the kind of person who can be trusted completely and who always follows through.", fullText: `Your Personality Number 4 projects an aura of reliability, practicality, and grounded competence. People perceive you as someone who has their life together, who can be counted on in a crisis, and whose word is as solid as a handshake with bedrock. You radiate stability.\n\nYour first impression communicates trustworthiness and efficiency. Others see you as organized, methodical, and serious about your responsibilities. Your appearance tends to be neat, conservative, and appropriate — you instinctively understand the importance of presenting yourself in a way that commands professional respect.\n\nThis solid persona is your greatest asset in building long-term trust and professional credibility. However, be aware that others may perceive you as rigid or overly serious. Occasionally showing your lighter, more spontaneous side can round out others' perception and prevent them from typecasting you as all work and no play.` },
  5: { title: "The Magnetic Presence", keywords: ["Dynamic", "Exciting", "Versatile"], shortDesc: "The world sees you as dynamic, exciting, and irresistibly magnetic — someone who brings energy and adventure wherever they go.", fullText: `Your Personality Number 5 creates a first impression of dynamism, excitement, and magnetic versatility. People perceive you as someone who lives life at full volume — adventurous, daring, and impossible to ignore. Your energy communicates freedom, spontaneity, and a delicious unpredictability.\n\nYour outward persona attracts attention effortlessly. Others see you as worldly, progressive, and sexually magnetic. You tend to dress in ways that express your individuality, often ahead of trends. Your body language is open, expressive, and communicates an invitation to adventure.\n\nThis electric persona makes you incredibly compelling in social and professional situations that value innovation and dynamism. However, some may struggle to pin you down, wondering if your exciting exterior masks a lack of depth or commitment. Demonstrating follow-through on important matters helps others trust your substance as much as they enjoy your sparkle.` },
  6: { title: "The Nurturing Presence", keywords: ["Caring", "Responsible", "Beautiful"], shortDesc: "Others see you as a caring, responsible, and aesthetically refined individual — someone who creates beauty and warmth wherever they go.", fullText: `Your Personality Number 6 projects an aura of warmth, responsibility, and aesthetic refinement. People perceive you as someone who genuinely cares about others' wellbeing and who possesses a natural eye for beauty and harmony. You radiate domestic grace and emotional availability.\n\nYour first impression is one of nurturing competence. Others see you as a natural caretaker, someone they can trust with their hearts and their homes. You tend to dress with classic elegance, and your appearance communicates that you care about details and quality.\n\nThis nurturing persona makes you deeply valued in any community or relationship. However, be aware that others may take your caretaking for granted or assume you're always willing to put their needs first. Setting clear boundaries while maintaining your natural warmth teaches others to reciprocate the care you so generously offer.` },
  7: { title: "The Mysterious Presence", keywords: ["Enigmatic", "Intelligent", "Reserved"], shortDesc: "The world perceives you as mysterious, intellectually sophisticated, and perhaps slightly enigmatic — someone whose depth is intriguing.", fullText: `Your Personality Number 7 creates an impression of mystery, intelligence, and refined reserve. People perceive you as someone who operates on a deeper level than most — an enigmatic figure whose quiet intensity suggests profound inner worlds. You radiate the energy of the thinker, the philosopher, the one who sees what others miss.\n\nYour first impression is one of intellectual sophistication and deliberate distance. Others may find you fascinating precisely because you don't give everything away at once. You tend to dress with understated elegance or quiet individuality, projecting taste without ostentation.\n\nThis mysterious persona attracts people who value depth and substance. However, it can also intimidate those who mistake your reserve for aloofness or judgment. Making small gestures of warmth — a genuine smile, a thoughtful question — can bridge the gap between your private inner world and others' desire to connect with you.` },
  8: { title: "The Powerful Presence", keywords: ["Authoritative", "Successful", "Commanding"], shortDesc: "Others see you as powerful, authoritative, and commanding — someone whose presence speaks of success, ambition, and material mastery.", fullText: `Your Personality Number 8 projects an aura of power, success, and executive authority. People perceive you as someone who operates at a high level — confident, ambitious, and clearly accustomed to positions of influence. Your presence alone communicates competence and the expectation of being taken seriously.\n\nYour first impression is formidable. Others see you as someone who has achieved (or is clearly destined to achieve) significant material success. You tend to dress in ways that communicate status and professionalism, instinctively understanding that appearance is a tool of power.\n\nThis commanding persona opens doors in the business world and positions of leadership. However, it can create emotional distance in personal relationships, where people may feel intimidated or assume you're all business. Showing your human side — your humor, your vulnerabilities, your capacity for tenderness — reveals the warmth beneath the power suit.` },
  9: { title: "The Noble Presence", keywords: ["Compassionate", "Worldly", "Idealistic"], shortDesc: "The world sees you as compassionate, worldly, and idealistic — someone whose noble bearing suggests both wisdom and genuine concern for humanity.", fullText: `Your Personality Number 9 creates an impression of nobility, compassion, and worldly sophistication. People perceive you as someone who carries themselves with the dignity of an old soul — wise, tolerant, and genuinely concerned with the greater good. You radiate an aura of having lived many lives and gathered wisdom from each one.\n\nYour first impression is one of quiet authority combined with accessible warmth. Others see you as someone they can learn from, someone whose broad perspective makes them feel less alone in the world. You tend to have eclectic taste in dress and surroundings, reflecting your appreciation for diverse cultures.\n\nThis noble persona inspires trust and admiration. However, others may sometimes feel that you're emotionally distant, processing the world through your idealistic vision rather than engaging in raw, messy human connection. Letting people see your struggles as well as your wisdom creates deeper bonds.` },
  11: { title: "The Luminous Presence", keywords: ["Inspiring", "Magnetic", "Otherworldly"], shortDesc: "Others perceive something otherworldly about you — a luminous, inspiring quality that suggests you operate on a different frequency entirely.", fullText: `Your Master Personality Number 11 creates an impression that's genuinely unusual — people sense something otherworldly about you, a quality of light or inspiration that sets you apart from ordinary social interactions. You project an aura of spiritual depth and creative brilliance that can be both magnetic and slightly intimidating.\n\nPeople may not be able to articulate exactly what it is about you that captivates them, but they feel it. Your presence inspires others to think bigger, dream more boldly, and consider possibilities they might otherwise dismiss. You possess a natural spotlight quality that draws attention without effort.\n\nThis luminous persona is a powerful gift, but it can also create challenges. Others may project their ideals onto you, placing you on a pedestal and then feeling disappointed when you prove to be human. Managing others' expectations while staying true to your authentic self is an ongoing balancing act.` },
  22: { title: "The Monumental Presence", keywords: ["Commanding", "Visionary", "Substantial"], shortDesc: "You project the aura of someone destined for monumental achievement — a Master Builder whose very presence commands respect and inspires ambition.", fullText: `Your Master Personality Number 22 creates an impression of substantial, almost monumental authority. People perceive you as someone whose scope of vision and capacity for achievement operates on a level that most can barely comprehend. Your presence communicates that you think bigger, plan longer, and build more solidly than anyone else in the room.\n\nThis is not merely confidence — it's the projection of genuine capability at the highest level. Others sense that your ambitions aren't fantasies but blueprints, and that you possess the discipline and vision to transform them into reality.\n\nThis powerful projection naturally attracts resources, collaborators, and opportunities. However, it can also overwhelm people who aren't accustomed to operating at your frequency. Learning to calibrate your intensity for different audiences helps you connect with a wider range of people.` },
  33: { title: "The Radiant Presence", keywords: ["Healing", "Loving", "Transcendent"], shortDesc: "Others perceive an almost saint-like quality in you — a radiant compassion and spiritual warmth that heals simply through your presence.", fullText: `Your Master Personality Number 33 projects the rarest aura — one of pure, unconditional love and healing warmth. People perceive something almost transcendent about you, a quality of compassion so genuine and deep that it can bring tears to the eyes of strangers. Your presence itself is healing.\n\nOthers are drawn to your light instinctively, often sharing their deepest pain within moments of meeting you. You project safety, understanding, and a kind of spiritual authority that comes not from power but from love. Your energy communicates: 'You are safe here. You are loved.'\n\nThis extraordinarily beautiful persona is both your greatest gift and your greatest vulnerability. Others may drain your energy if you don't maintain boundaries, and the weight of being everyone's healer can be exhausting. Remember that even the brightest light needs regular renewal.` },
};

export const birthdayInterpretations: Record<number, string> = {
  1: "Born on a day ruled by the number 1, you carry the gift of initiative and original thinking. You possess a natural ability to start new projects and inspire others through your independent spirit. Your birth day endows you with courage and the confidence to forge your own path.",
  2: "Your birthday gift is the power of cooperation and intuition. You have an exceptional ability to sense the needs of others and bring harmony to any situation. Your natural diplomacy and patience are talents that serve you throughout your life.",
  3: "Born under the creative vibration of 3, your special gift is self-expression. You have a natural way with words, a quick wit, and an artistic sensibility that allows you to communicate complex ideas with grace and charm. Your optimism is contagious.",
  4: "Your birthday blesses you with the gift of practical mastery. You possess an extraordinary ability to organize, plan, and execute. Where others dream, you build. Your attention to detail and rock-solid reliability are gifts the world desperately needs.",
  5: "Born on a day vibrating with the energy of 5, your gift is adaptability and quick thinking. You can assess any situation instantly and adjust your approach accordingly. Your natural versatility makes you effective in rapidly changing environments.",
  6: "Your birthday gift is the ability to nurture and heal through love. You possess an innate understanding of what others need to feel safe and valued. Your aesthetic sense and devotion to beauty make you a natural creator of harmonious environments.",
  7: "Born under the contemplative energy of 7, your special gift is analytical intuition — the rare ability to combine logical analysis with deep intuitive knowing. You see patterns others miss and arrive at insights that seem almost prophetic.",
  8: "Your birthday endows you with the gift of executive ability and material mastery. You possess a natural understanding of power dynamics, resource management, and strategic thinking that positions you for significant achievement and influence.",
  9: "Born on a day ruled by 9, your gift is universal compassion and broad-minded wisdom. You possess an extraordinary ability to see the big picture, to understand diverse perspectives, and to inspire others toward their highest potential through your generous spirit.",
};

export const personalYearInterpretations: Record<number, NumberInterpretation> = {
  1: { title: "Year of New Beginnings", keywords: ["Fresh Start", "Initiative", "Independence"], shortDesc: "This is YOUR year to plant seeds. New beginnings, bold moves, and fresh starts are cosmically supported right now.", fullText: `Welcome to a Personal Year 1 — the most powerful new beginning in the entire 9-year numerological cycle. This is the year when the universe clears the stage and hands you the spotlight. Everything you initiate this year carries special momentum, making this the ideal time to launch new projects, change directions, and assert your independence.\n\nThe energy of this year supports boldness and originality. Decisions you've been postponing? Make them now. Ideas you've been nurturing quietly? It's time to bring them into the light. The cosmic currents are flowing in the direction of new creation, and you'll find that opportunities seem to materialize from unexpected sources.\n\nWhat to focus on: Starting that business, making that move, beginning that creative project, asserting yourself in relationships, setting new personal goals. Be the initiator in every area of your life.\n\nWhat to avoid: Clinging to the past, waiting for others to act first, playing it safe when your intuition is screaming 'GO.' Passivity is your enemy this year. The universe rewards action.\n\nThis is a year of planting seeds that will grow over the next nine years. Choose wisely what you want to cultivate, because the energy you set in motion now will shape your reality for years to come.` },
  2: { title: "Year of Partnership & Patience", keywords: ["Cooperation", "Relationships", "Waiting"], shortDesc: "After last year's bold moves, this year asks you to slow down, nurture relationships, and practice the art of patient collaboration.", fullText: `Your Personal Year 2 is a time of cooperation, patience, and the quiet work of nurturing what you planted in your Year 1. If last year was about bold action, this year is about gentle cultivation. The seeds you planted need water, sunlight, and time — not more seeds.\n\nRelationships take center stage this year. Partnerships of all kinds — romantic, business, creative — are highlighted and supported by the cosmic energy. This is an excellent year for deepening existing bonds, resolving long-standing conflicts, and developing the diplomatic skills that will serve you throughout the rest of this cycle.\n\nWhat to focus on: Building relationships, developing patience, paying attention to details you may have overlooked, listening more than speaking, collaborating rather than competing.\n\nWhat to avoid: Forcing outcomes, being impatient with slow progress, neglecting your emotional needs, taking on too many new projects. This is a year of gestation, not germination.\n\nThe lesson of Year 2 is that some of life's most important work happens in stillness. Trust the process. What you planted last year is growing, even when you can't see the evidence yet.` },
  3: { title: "Year of Creative Expression", keywords: ["Creativity", "Joy", "Social Life"], shortDesc: "Your creative energy is at its peak! This is the year to express yourself, socialize, and let your joyful, artistic spirit shine.", fullText: `Your Personal Year 3 arrives with a burst of creative energy, social opportunity, and joyful self-expression. After the quiet patience of Year 2, this year invites you to come out of your shell and share your gifts with the world. Your natural charisma is amplified, making this an ideal time for any form of creative or communicative endeavor.\n\nThis is a year when your words carry extra power and your creative ideas flow with unusual ease. Writing, speaking, performing, designing, singing — whatever form your creativity takes, it's cosmically supported right now. Your social life expands naturally, bringing new connections that inspire and energize you.\n\nWhat to focus on: Creative projects, social networking, self-expression, personal branding, taking classes, traveling, enjoying life's pleasures, sharing your ideas publicly.\n\nWhat to avoid: Self-doubt, isolating yourself, being overly critical of your creative output, scattering your energy across too many projects without completing any of them.\n\nThe gift of Year 3 is the reminder that joy is not frivolous — it's fuel. When you allow yourself to play, create, and connect, you generate the positive energy that powers everything else in your life.` },
  4: { title: "Year of Building Foundations", keywords: ["Hard Work", "Structure", "Discipline"], shortDesc: "Time to get serious. This year demands discipline, hard work, and the building of solid foundations for your future success.", fullText: `Your Personal Year 4 brings a shift from the playful energy of Year 3 to a more serious, disciplined vibration. This is the year of building — creating the structures, systems, and foundations that will support your dreams for years to come. It may not be glamorous, but it's essential.\n\nThe universe is asking you to roll up your sleeves and do the hard work that transforms inspiration into reality. This is the year to get organized, create budgets, establish routines, take care of your health, and invest in the practical infrastructure of your life. Shortcuts will backfire; thorough, methodical effort will be richly rewarded.\n\nWhat to focus on: Financial planning, health routines, home improvements, career development, skill-building, establishing systems and processes, addressing practical matters you've been avoiding.\n\nWhat to avoid: Taking shortcuts, neglecting your physical health, overworking without rest, resisting the discipline this year requires. Fighting the 4 energy is exhausting — work with it, and it becomes your greatest ally.\n\nThe lesson of Year 4 is that true freedom is built on a foundation of discipline. The structures you create this year aren't constraints — they're the solid ground from which your future dreams will launch.` },
  5: { title: "Year of Change & Freedom", keywords: ["Change", "Adventure", "Transformation"], shortDesc: "Hold on tight — this is a year of dramatic change, unexpected opportunities, and the exciting freedom to reinvent yourself.", fullText: `Your Personal Year 5 arrives like a lightning bolt after the hard-working stability of Year 4. Change is not just possible this year — it's inevitable. The universe is shaking things up, breaking you free from routines and structures that have served their purpose, and opening doors to experiences you never expected.\n\nThis is the most dynamic and unpredictable year in the entire 9-year cycle. Travel, relocation, career changes, new relationships, and dramatic personal transformations are all cosmically supported. Your craving for freedom and variety is at its peak, and the energy to pursue it is abundant.\n\nWhat to focus on: Embracing change rather than resisting it, traveling, trying new things, meeting new people, being open to opportunities that arrive unexpectedly, physical health and vitality.\n\nWhat to avoid: Clinging to the old when everything is pointing toward the new, overindulging in sensory pleasures, making impulsive decisions without any grounding. Freedom without responsibility leads to chaos.\n\nThe gift of Year 5 is the reminder that life is meant to be experienced fully. Change isn't something that happens to you — it's something that happens for you, expanding your horizons and revealing parts of yourself you didn't know existed.` },
  6: { title: "Year of Love & Responsibility", keywords: ["Family", "Love", "Service"], shortDesc: "Love, family, and responsibility take center stage. This is a year of deepening bonds, domestic focus, and heartfelt service to those you love.", fullText: `Your Personal Year 6 brings the focus squarely back to love, family, and domestic responsibility after the whirlwind adventure of Year 5. This is a year of the heart — when your relationships, home life, and sense of duty to those you love take absolute priority.\n\nMarriages, engagements, pregnancies, and significant family events are common during a Year 6. Your nurturing instincts are heightened, and you may find yourself called upon to take on greater responsibility for family members or community. Beauty, comfort, and harmony in your home environment become important to your wellbeing.\n\nWhat to focus on: Strengthening family bonds, improving your home, deepening romantic relationships, serving your community, addressing health concerns, creating beauty in your environment.\n\nWhat to avoid: Neglecting your own needs while caring for everyone else, being controlling or smothering in relationships, avoiding responsibility, sacrificing yourself to the point of resentment.\n\nThe lesson of Year 6 is that love is an action verb. This year asks you to demonstrate your love through tangible acts of care, commitment, and service — and to receive love as gracefully as you give it.` },
  7: { title: "Year of Inner Wisdom", keywords: ["Reflection", "Spirituality", "Study"], shortDesc: "The universe invites you inward. This is a year of deep reflection, spiritual growth, study, and the development of inner wisdom.", fullText: `Your Personal Year 7 is the most introspective year in the entire cycle — a sacred time of turning inward, studying deeply, and developing the spiritual wisdom that will guide you through the years ahead. After the outward focus of Year 6, this year asks you to retreat from the world's noise and listen to the quiet voice within.\n\nThis is an excellent year for formal study, spiritual practice, therapy, research, and any form of deep inner work. Your intuition is especially sharp, and insights that arrive through meditation, contemplation, or quiet reflection can be profoundly transformative. Solitude isn't loneliness this year — it's luxury.\n\nWhat to focus on: Meditation, study, therapy, spiritual development, spending time in nature, reading, journaling, developing your intuition, quality over quantity in all areas.\n\nWhat to avoid: Excessive socializing when you need solitude, superficial activities that waste your precious introspective energy, ignoring your intuitive guidance, trying to force external results when the real work is internal.\n\nThe gift of Year 7 is self-knowledge — the deep, honest understanding of who you are, what you truly want, and what wisdom you've accumulated through your journey so far.` },
  8: { title: "Year of Abundance & Power", keywords: ["Success", "Money", "Achievement"], shortDesc: "This is your harvest year! Financial success, career advancement, and material abundance are powerfully supported by the cosmic energy.", fullText: `Your Personal Year 8 is the most powerful year for material achievement and financial success in the entire 9-year cycle. Everything you've been building, learning, and developing over the past seven years reaches its culmination now. This is harvest time — when your efforts bear tangible, often spectacular fruit.\n\nCareer advancement, business success, significant financial gains, and recognition for your achievements are all strongly supported. Your personal power is at its peak, and your ability to manifest your goals in the material world is remarkably enhanced. This is the year to think big, negotiate boldly, and claim what you've earned.\n\nWhat to focus on: Career advancement, financial investments, business expansion, leadership opportunities, physical fitness, claiming your authority, managing resources wisely.\n\nWhat to avoid: Greed, power games, neglecting relationships in pursuit of success, spending recklessly, becoming arrogant about your achievements. The 8 energy rewards wisdom as much as ambition.\n\nThe lesson of Year 8 is that true abundance encompasses all areas of life. Material success is wonderful, but it's most fulfilling when shared generously and combined with healthy relationships, physical vitality, and spiritual awareness.` },
  9: { title: "Year of Completion & Release", keywords: ["Endings", "Release", "Transformation"], shortDesc: "A powerful year of endings and release. Clear out the old to make way for the magnificent new cycle about to begin.", fullText: `Your Personal Year 9 marks the completion of your current 9-year cycle — a powerful, often emotional year of endings, release, and transformation. This is the year to close chapters, tie up loose ends, and release everything that no longer serves your highest good. What you carry forward should be only what truly nourishes your soul.\n\nThis can be an intensely emotional year as relationships, jobs, habits, and even beliefs that have been with you for years reach their natural conclusion. Resist the urge to cling to what's ending. The universe is clearing space for the magnificent new cycle that begins next year with your Personal Year 1.\n\nWhat to focus on: Completing unfinished projects, forgiving old grudges, releasing toxic relationships, charitable work, creative expression, preparing for new beginnings, practicing gratitude.\n\nWhat to avoid: Starting major new ventures (wait for Year 1), clinging to relationships or situations that are clearly ending, dwelling on the past, resisting the natural process of release.\n\nThe gift of Year 9 is wisdom through completion. Every ending this year is making space for something better. Trust the process of release, grieve what needs grieving, and prepare yourself for the extraordinary new beginning that awaits just around the corner.` },
  11: { title: "Year of Spiritual Awakening", keywords: ["Illumination", "Intuition", "Higher Purpose"], shortDesc: "A rare Master Number year of heightened spiritual awareness, profound intuitive insights, and alignment with your higher purpose.", fullText: `Your Personal Year 11 is extraordinarily rare — a Master Number year of spiritual awakening, heightened intuition, and alignment with your soul's highest purpose. This year operates at a frequency that transcends ordinary experience, offering you glimpses of truth and moments of illumination that can transform your entire life direction.\n\nPay close attention to your dreams, synchronicities, and intuitive flashes this year. The universe is communicating with you through channels that require quiet attention. You may experience a spiritual awakening, a profound creative inspiration, or a calling to service that reshapes your understanding of why you're here.\n\nWhat to focus on: Spiritual development, creative expression, following intuitive guidance, inspirational leadership, teaching and mentoring, developing your psychic sensitivity.\n\nWhat to avoid: Ignoring spiritual promptings, excessive materialism, nervous tension from fighting the heightened sensitivity, trying to rationalize experiences that transcend rational understanding.\n\nThe gift of a Year 11 is illumination — a light that, once seen, cannot be unseen.` },
  22: { title: "Year of Master Building", keywords: ["Legacy", "Grand Achievement", "Manifestation"], shortDesc: "An incredibly powerful Master Number year for manifesting your grandest vision into concrete, world-changing reality.", fullText: `Your Personal Year 22 is one of the most powerful possible — the Master Builder year when your grandest visions can be manifested into concrete reality. The scope of what's available to you this year is staggering, as the universe aligns circumstances to support achievement on a scale that most people never experience.\n\nThis is the year for launching major enterprises, creating lasting institutions, and building legacy projects that will serve generations. Your capacity for strategic planning and practical execution is at its absolute peak, supported by visionary insight that ensures you're building something truly meaningful.\n\nWhat to focus on: Large-scale projects, institutional development, legacy building, strategic planning, practical implementation of grand visions, leadership at the highest level.\n\nWhat to avoid: Thinking too small, allowing fear to limit your scope, perfectionism that prevents you from starting, neglecting self-care in the pursuit of grand achievement.\n\nThe gift of a Year 22 is the realization that you are capable of far more than you ever imagined.` },
};

export function getInterpretation(type: string, number: number): NumberInterpretation | undefined {
  const maps: Record<string, Record<number, NumberInterpretation>> = {
    lifePath: lifePathInterpretations,
    expression: expressionInterpretations,
    soulUrge: soulUrgeInterpretations,
    personality: personalityInterpretations,
    personalYear: personalYearInterpretations,
  };
  return maps[type]?.[number];
}
