export interface NumberInterpretation {
  title: string;
  keywords: string[];
  shortDesc: string;
  fullText: string;
  famousPeople?: string[];
}

export const lifePathInterpretations: Record<number, NumberInterpretation> = {
  1: {
    title: "The Pioneer",
    keywords: ["Independence", "Leadership", "Innovation", "Courage"],
    shortDesc: "A born leader who forges their own path with fierce independence and raw creative courage.",
    famousPeople: ["Martin Luther King Jr.", "Steve Jobs", "Lady Gaga", "Tom Hanks"],
    fullText: `You carry the energy of the trailblazer — the one who goes first. Your soul resonates with new beginnings, original ideas, and the courage to stand alone. Where others see dead ends, you see doorways. Your presence commands attention not through force, but through the magnetism of someone who knows exactly who they are.

Your shadow is stubbornness and isolation. Your fierce independence can push away the connections that would enrich your journey. The lesson: lead with compassion, not just conviction. You're not meant to blend in — you're meant to light the way. Every great movement began with one person who dared to think differently. That person is you.`,
  },
  2: {
    title: "The Peacemaker",
    keywords: ["Diplomacy", "Partnership", "Sensitivity", "Harmony"],
    shortDesc: "A natural mediator with profound empathy and the rare gift of uniting opposing forces.",
    famousPeople: ["Barack Obama", "Madonna", "Emma Watson", "Kanye West"],
    fullText: `Your greatest power lies in subtlety. You possess an almost psychic ability to read the emotional currents in any room, sensing tensions that others miss entirely. People trust you instinctively because you genuinely care — and they can feel it. Your patience, your talent for seeing both sides, and your ability to create beauty and harmony make you extraordinary.

Your shadow is self-erasure. You may suppress your own needs to maintain peace, but this breeds resentment. True harmony includes your voice. Being a peacemaker doesn't mean being a doormat. You're here to demonstrate that collaboration creates more powerful outcomes than competition — that connection beats conquest.`,
  },
  3: {
    title: "The Creative Spirit",
    keywords: ["Expression", "Joy", "Communication", "Artistry"],
    shortDesc: "A radiant creative force born to inspire through self-expression, joy, and artistic vision.",
    famousPeople: ["John Travolta", "Celine Dion", "Snoop Dogg", "Hillary Clinton"],
    fullText: `Creativity isn't something you do — it's who you are. Your mind generates ideas at a dizzying pace. You see beauty in unexpected places, find humor in absurdity, and carry a charisma that makes you unforgettable. Communication flows through you effortlessly — stories, poems, laughter. You carry a frequency of joy the world desperately needs.

Your shadow is scattered energy and hidden self-doubt beneath the cheerful exterior. Unexpressed feelings lead to moodiness or escapism. Your mission: use your creative gifts to heal, inspire, and connect. You're here to remind humanity that joy is not frivolous — it is essential.`,
  },
  4: {
    title: "The Builder",
    keywords: ["Structure", "Discipline", "Stability", "Dedication"],
    shortDesc: "The master builder who turns dreams into reality through discipline and unwavering dedication.",
    famousPeople: ["Oprah Winfrey", "Elton John", "Arnold Schwarzenegger", "Bill Gates"],
    fullText: `While others dream and drift, you dig in and build things that endure. You value integrity above all — when you give your word, it is absolute. Your exceptional organizational skills, patience with detail, and ability to see projects through from start to finish give you a stamina others envy. Where they burn out, you persist.

Your shadow is rigidity. Your love of structure can become a prison. You may resist necessary change, clinging to routines that no longer serve you. The lesson: the strongest structures are those that can bend. Your mission is to leave behind something tangible and enduring — to ensure humanity's greatest ideas don't remain just ideas.`,
  },
  5: {
    title: "The Freedom Seeker",
    keywords: ["Adventure", "Change", "Freedom", "Versatility"],
    shortDesc: "An eternal adventurer driven by insatiable curiosity and a deep need for freedom.",
    famousPeople: ["Angelina Jolie", "Abraham Lincoln", "Beyoncé", "Vincent van Gogh"],
    fullText: `Routine is your kryptonite; the unknown is your playground. You possess extraordinary versatility — the chameleon of the numerological world, able to reinvent yourself and connect with people from wildly different backgrounds. Your natural charm and quick wit make you irresistible company. Your progressive thinking often places you ahead of your time.

Your shadow is excess and commitment-phobia. Your hunger for stimulation can lead to overindulgence or spreading yourself too thin. The profound lesson: true freedom includes the freedom to commit. You're the bridge between worlds — gathering wisdom through diverse experiences and sharing those insights so others can expand their own boundaries.`,
  },
  6: {
    title: "The Nurturer",
    keywords: ["Responsibility", "Love", "Healing", "Home"],
    shortDesc: "A cosmic healer devoted to love, family, and creating beauty in all relationships.",
    famousPeople: ["John Lennon", "Albert Einstein", "Eleanor Roosevelt", "Michael Jackson"],
    fullText: `Your heart is vast, your compassion seemingly limitless. You possess a remarkable aesthetic sense and infuse everything with grace and warmth — decorating a home, counseling a friend, simply arranging flowers. People are drawn to your loving presence because with you, they feel safe and understood in a way that's increasingly rare.

Your shadow is martyrdom. Your desire to help can become controlling. You sacrifice your wellbeing and feel bitter when it's not reciprocated. The essential lesson: you cannot pour from an empty cup. Sometimes the most loving thing is allowing others to struggle and grow. You're here to teach love through example — creating sanctuaries where people can heal.`,
  },
  7: {
    title: "The Seeker",
    keywords: ["Wisdom", "Introspection", "Mystery", "Spirituality"],
    shortDesc: "A mystic philosopher driven by an unquenchable thirst for truth and inner wisdom.",
    famousPeople: ["Princess Diana", "Elon Musk", "Leonardo DiCaprio", "Stephen Hawking"],
    fullText: `While others accept surface-level explanations, you must go deeper. You need to understand the why behind the what. Your mind is extraordinary — analytical yet intuitive, scientific yet spiritual. You hold seemingly contradictory truths simultaneously, understanding that reality is far more nuanced and mysterious than most acknowledge.

Your shadow is isolation and cynicism. Your need for solitude can become excessive, cutting you off from connections that nourish your growth. Perfectionism can paralyze you. Your mission: bridge the seen and unseen worlds. Dive deep into mysteries, then surface with pearls of insight that illuminate the path for others.`,
  },
  8: {
    title: "The Powerhouse",
    keywords: ["Authority", "Abundance", "Achievement", "Material Mastery"],
    shortDesc: "A manifestation master destined for material success and transformative leadership.",
    famousPeople: ["Nelson Mandela", "Pablo Picasso", "Sandra Bullock", "50 Cent"],
    fullText: `The universe didn't design you to play small. You carry the vibration of abundance, achievement, and executive leadership. Unlike other Life Paths, you're not meant to transcend material concerns — you're meant to master them. You possess innate business acumen, a strategic mind, and relentless drive. When you set your sights on a goal, the universe conspires to help you achieve it.

Your shadow is workaholism and measuring worth solely by your bank account. True abundance encompasses all areas of life. Your mission: demonstrate that material success and spiritual integrity aren't mutually exclusive. Build empires that serve humanity — power wielded with wisdom is a force for tremendous good.`,
  },
  9: {
    title: "The Humanitarian",
    keywords: ["Compassion", "Wisdom", "Completion", "Universal Love"],
    shortDesc: "An old soul driven by universal love and a mission to serve the greater good.",
    famousPeople: ["Mahatma Gandhi", "Mother Teresa", "Jimi Hendrix", "Morgan Freeman"],
    fullText: `You vibrate at the highest single-digit frequency. Your perspective is remarkably broad — while others focus on personal concerns, you naturally see the interconnectedness of all things, the patterns connecting seemingly unrelated events. This gives you a wisdom and tolerance that can seem almost otherworldly. Your magnetism draws people from all walks of life.

Your shadow is clinging. Despite being the number of completion, you may struggle fiercely with release — holding onto relationships and identities past their expiration. The most important lesson: endings are sacred, creating space for new beginnings. Your mission is nothing less than the elevation of human consciousness through compassion.`,
  },
  11: {
    title: "The Illuminator",
    keywords: ["Intuition", "Inspiration", "Spiritual Messenger", "Visionary"],
    shortDesc: "A Master Number — a spiritual messenger whose heightened intuition illuminates the world.",
    famousPeople: ["Michelle Obama", "Wolfgang Mozart", "David Beckham", "Edgar Allan Poe"],
    fullText: `You walk between worlds, serving as a bridge between the mundane and the mystical. Your intuition borders on the prophetic — you experience extreme sensitivity, vivid dreams, and a persistent feeling that you're here for something significant. You are an antenna for cosmic energy, receiving signals from a frequency most can't detect.

Your shadow is nervous tension and paralyzing self-doubt. The gap between your spiritual potential and human reality creates intense anxiety. Without grounding, the 11 energy manifests as anxiety or paralysis. Your mission: be a spiritual lighthouse — channel divine inspiration into forms that uplift and awaken others. Your path is not easy, but it is profoundly meaningful.`,
  },
  22: {
    title: "The Master Builder",
    keywords: ["Mastery", "Vision", "Legacy", "Transformation"],
    shortDesc: "The most powerful Master Number — destined to build something of lasting significance for all humanity.",
    famousPeople: ["Paul McCartney", "the Dalai Lama", "Will Smith", "Richard Branson"],
    fullText: `You possess the rare combination of visionary dreams and practical mastery, giving you the potential to turn the most ambitious visions into concrete reality. While others think in terms of personal success, you instinctively think in terms of legacy — structures and systems that serve humanity across generations.

Your shadow is crushing self-pressure. The weight of your potential can become paralyzing if you interpret it as obligation rather than invitation. Burnout is real. Your mission: leave a lasting legacy. Build bridges — literal or metaphorical — that connect people, ideas, and possibilities in ways that transform the world. You're not here for quick wins. You're here for something permanent.`,
  },
  33: {
    title: "The Master Healer",
    keywords: ["Unconditional Love", "Spiritual Teaching", "Healing", "Devotion"],
    shortDesc: "The rarest Master Number — a master teacher devoted to uplifting humanity through selfless love.",
    famousPeople: ["Albert Einstein (by some calculations)", "Meryl Streep", "Francis of Assisi"],
    fullText: `You embody the rarest and most elevated vibration in numerology. Your capacity to love is so vast it can seem almost inhuman in its scope. You don't just feel for individuals — you feel for humanity itself. This profound empathy, when channeled, gives you the ability to heal at levels others cannot even perceive.

Your shadow is depletion. Living at the 33 vibration requires selflessness that can be consuming without strong boundaries. You may attract codependent relationships or lose yourself in others' pain. The key lesson: you cannot heal the world if you neglect your own healing. Your mission is to be a master teacher of love — demonstrating that unconditional love is the most powerful force in existence.`,
  },
};

export const expressionInterpretations: Record<number, NumberInterpretation> = {
  1: { title: "The Original Thinker", keywords: ["Innovation", "Self-reliance", "Ambition"], shortDesc: "Your name encodes original thought and independent achievement — a destiny of pioneering leadership.", fullText: `Your name carries the vibration of the innovator. The universe embedded within it the seed of original thinking and self-directed achievement. You possess latent talents for entrepreneurship, creative problem-solving, and inspiring others through conviction.\n\nTo fulfill this vibration, trust your ideas even when they contradict popular opinion. Initiate rather than follow. The more you lean into your natural leadership, the more aligned you become with your true destiny.` },
  2: { title: "The Harmonizer", keywords: ["Cooperation", "Intuition", "Sensitivity"], shortDesc: "Your name encodes partnership and diplomacy — a destiny of uniting and harmonizing.", fullText: `Your name vibrates with the energy of the peacemaker. Your talents include extraordinary emotional intelligence, reading between lines, and creating consensus where others see only conflict. You are the glue that holds teams and communities together.\n\nEmbrace your receptive nature as strength, not passivity. Your destiny is fulfilled through roles that amplify others while quietly weaving the threads that hold everything together.` },
  3: { title: "The Communicator", keywords: ["Creativity", "Expression", "Joy"], shortDesc: "Your name blazes with creative fire — a destiny of inspiring and uplifting through artistic vision.", fullText: `Your name is a vessel for artistic expression and infectious joy. You have natural charisma that makes people want to listen, and a way with words that moves hearts. Humor comes naturally, and you understand that laughter is powerful medicine.\n\nResist scattering your energy across too many projects. Choose your medium and develop true mastery. When you focus your creative power, the results are nothing short of magical.` },
  4: { title: "The Organizer", keywords: ["Structure", "Reliability", "Hard Work"], shortDesc: "Your name carries the master organizer vibration — a destiny of creating enduring structures.", fullText: `Your name vibrates with reliability, hard work, and practical wisdom that turns chaos into order. You possess an instinctive understanding of how things fit together — structures, systems, organizations. People trust you because your word is your bond.\n\nEmbrace your role as the foundation-builder. Your path isn't glamorous, but every great achievement rests on the kind of solid foundation people like you create.` },
  5: { title: "The Adventurer", keywords: ["Freedom", "Versatility", "Change"], shortDesc: "Your name encodes freedom and versatile experience — a destiny of bridging different worlds.", fullText: `Your name vibrates with freedom, adaptability, and insatiable curiosity. You possess a magnetic personality effective in any field requiring quick thinking. Your versatility is remarkable — you can reinvent yourself more successfully than almost anyone.\n\nChannel your love of freedom into constructive paths. Your destiny: gather wisdom through diverse experiences, then serve as a bridge between different cultures, ideas, and perspectives.` },
  6: { title: "The Caretaker", keywords: ["Service", "Beauty", "Responsibility"], shortDesc: "Your name carries love, service, and aesthetic beauty — a destiny of nurturing and healing.", fullText: `Your name resonates with the cosmic caretaker — someone whose fulfillment comes through service to family, community, and ideals of beauty. You have an extraordinary aesthetic sense and can create harmony in spaces, relationships, and communities.\n\nBalance giving with receiving. Create environments of beauty and safety where others can heal — but not at the expense of your own wellbeing. The world needs you whole and healthy.` },
  7: { title: "The Analyst", keywords: ["Wisdom", "Research", "Spirituality"], shortDesc: "Your name vibrates with deep analysis and spiritual seeking — a destiny of uncovering hidden truths.", fullText: `Your name carries the vibration of the truth-seeker. You possess a mind that naturally goes deeper than surface appearances — brilliant at investigation, scientific inquiry, and philosophical contemplation. Your intuition is remarkably accurate when you learn to trust it.\n\nHonor both your need for solitude and your responsibility to share insights. Become a vessel for wisdom — gathering it through study and experience, then distilling it for others.` },
  8: { title: "The Executive", keywords: ["Power", "Achievement", "Material Mastery"], shortDesc: "Your name resonates with authority and material achievement — a destiny of powerful leadership.", fullText: `Your name vibrates with executive energy — natural command that positions you for leadership where important decisions are made. You possess business acumen, strategic thinking, and instinctive understanding of power dynamics.\n\nWield power with wisdom and generosity. Achieve material mastery not as an end, but as a means of creating positive change. The universe gave you tools for extraordinary achievement — use them for the greater good.` },
  9: { title: "The Philanthropist", keywords: ["Compassion", "Global Vision", "Completion"], shortDesc: "Your name carries the highest single-digit vibration — a destiny of universal service and artistic mastery.", fullText: `Your name resonates with the humanitarian and the artist whose vision extends beyond personal concerns. Your creative abilities are significant, and your work often carries a message of universal truth. You possess natural wisdom from seeing interconnectedness.\n\nLearn the art of letting go — releasing attachment to outcomes while maintaining passionate engagement. Your destiny involves completion and transformation, ending cycles and making space for new beginnings.` },
  11: { title: "The Visionary Messenger", keywords: ["Inspiration", "Revelation", "Channeling"], shortDesc: "A Master vibration of spiritual inspiration — destined to transmit visionary insights.", fullText: `Your name vibrates at a frequency that enables you to channel divine inspiration — receiving insights from higher dimensions and translating them into comprehensible forms. Your intuitive sensitivity borders on the clairvoyant.\n\nDevelop courage to share your visions even when they seem impractical. Balance the ethereal 11 energy with practical grounding. The world needs your spiritual insights communicated in accessible, practical ways.` },
  22: { title: "The Architect of Destiny", keywords: ["Grand Vision", "Practical Mastery", "World Impact"], shortDesc: "The Master Builder vibration — the highest potential for manifesting vision into reality on a global scale.", fullText: `Your name resonates with the Master Builder frequency — combining spiritual illumination with practical mastery. You see potential where others see limitations, and possess the skills to turn possibilities into realities.\n\nResist playing small. Your path is monumental achievement for service, not ego. Build structures and systems that serve not just this generation, but generations to come.` },
  33: { title: "The Master Teacher of Love", keywords: ["Selfless Service", "Cosmic Love", "Spiritual Mastery"], shortDesc: "The highest Master Number — a rare destiny of spiritual mastery through unconditional love.", fullText: `Your name encodes the potential for profound spiritual mastery — the cosmic healer whose love transcends personal attachment. Your presence alone can shift the energy of a room, calming anxiety and awakening hope.\n\nEmbrace your role as a beacon of unconditional love while maintaining personal boundaries. The world needs your healing presence and your unwavering demonstration that love is the most powerful force in existence.` },
};

export const soulUrgeInterpretations: Record<number, NumberInterpretation> = {
  1: { title: "The Independent Heart", keywords: ["Autonomy", "Self-direction", "Originality"], shortDesc: "Deep inside, you crave complete independence and the freedom to follow your own unique path.", fullText: `Beneath everything you show the world, your deepest desire is for independence and the freedom to be completely, authentically yourself. You feel most fulfilled when pioneering something new, leading by your own vision, proving your unique approach has value.\n\nThis drive makes you restless in environments demanding conformity. Stop apologizing for your need to be an individual — start honoring it as the sacred impulse it truly is.` },
  2: { title: "The Loving Heart", keywords: ["Connection", "Peace", "Partnership"], shortDesc: "Your deepest desire is for profound emotional connection that makes you feel truly seen.", fullText: `More than success, recognition, or adventure, what your soul craves is to love and be loved in a way that feels genuinely reciprocal. Harmony in your environment isn't luxury — it's necessity. Discord affects you at a cellular level.\n\nYour sensitivity is your gift, but it makes you vulnerable to losing yourself in relationships. The deepest connection begins with connection to yourself — know and love who you are before merging with another.` },
  3: { title: "The Joyful Heart", keywords: ["Self-expression", "Creativity", "Recognition"], shortDesc: "At your core, you long to express yourself fully and be appreciated for your unique creative gifts.", fullText: `Your soul doesn't just want to create — it needs to create the way lungs need to breathe. Without an outlet for your creative energy, you feel suffocated. Recognition matters not because you're vain, but because it confirms your inner world has value.\n\nIf you feel inexplicably depressed, check whether your creative expression has been stifled. Make space for creativity daily — it's not a hobby, it's a soul requirement.` },
  4: { title: "The Grounded Heart", keywords: ["Security", "Order", "Achievement"], shortDesc: "Deep within, you crave stability and the satisfaction of building something lasting.", fullText: `Your soul seeks the profound satisfaction of creating enduring value. You feel most fulfilled with a clear plan, solid routine, and tangible evidence your efforts produce lasting results. There's a craftsman quality to your nature — deep satisfaction from mastering skills and doing things properly.\n\nUncertainty genuinely disturbs your inner peace. Honor your need for structure while allowing room for growth — both are essential.` },
  5: { title: "The Free Heart", keywords: ["Freedom", "Experience", "Stimulation"], shortDesc: "Your soul burns with desire for freedom, variety, and experiencing everything life offers.", fullText: `You feel most alive experiencing something new — a new place, idea, person, sensation. Routine is physically painful for your soul. You need variety the way others need stability, and without it you feel like a caged bird.\n\nTrue freedom isn't about running away — it's having the courage to run toward your deepest truth. That distinction changes everything.` },
  6: { title: "The Devoted Heart", keywords: ["Love", "Family", "Beauty"], shortDesc: "Your soul yearns to love completely and create a life filled with beauty and harmony.", fullText: `More than anything, your soul longs to create a sanctuary where those you care about feel safe, valued, and nourished. Aesthetic harmony isn't superficial — it reflects the inner harmony your soul craves. You are genuinely distressed by ugliness, discord, and injustice.\n\nYour desire to help can cross into codependency. Extend the same loving devotion to yourself that you so naturally offer to others.` },
  7: { title: "The Seeking Heart", keywords: ["Truth", "Solitude", "Understanding"], shortDesc: "Deep within, your soul craves spiritual understanding and the revelation of hidden truths.", fullText: `Your soul hungers for genuine wisdom — authentic understanding of life's mysteries, and the peace that comes from knowing rather than merely believing. Solitude isn't lonely for you — it's luxurious. In silence, you hear answers to questions most haven't thought to ask.\n\nYour need for privacy and discomfort with small talk makes perfect sense once you understand this drive. Structure your life to honor depth while maintaining essential human connections.` },
  8: { title: "The Ambitious Heart", keywords: ["Power", "Success", "Recognition"], shortDesc: "Your soul is driven by achievement, authority, and success that commands respect.", fullText: `This isn't shallow ambition — it's a soul-level understanding that you're meant to operate at the highest levels, making decisions that matter. Financial security represents freedom, influence, and the ability to make things happen at a scale matching your inner vision.\n\nDon't let drive for achievement overshadow emotional connections. Deep down, you value relationships just as much as worldly accomplishments.` },
  9: { title: "The Compassionate Heart", keywords: ["Service", "Compassion", "Universal Love"], shortDesc: "Your soul yearns to serve humanity and contribute something meaningful to the world.", fullText: `Your soul operates on a universal frequency, feeling the joy and pain of humanity as if it were your own. Material pursuits feel empty unless connected to a larger purpose. You feel most fulfilled when making a difference — through art, teaching, healing, or simply being a compassionate presence.\n\nChannel your compassion effectively rather than burning out trying to save everyone. Serve without losing yourself in the process.` },
  11: { title: "The Inspired Heart", keywords: ["Revelation", "Spiritual Connection", "Higher Purpose"], shortDesc: "Your soul craves transcendent spiritual experience and channeling divine inspiration.", fullText: `Your deepest desire is direct connection with higher consciousness. You feel most fulfilled in moments of spiritual clarity — when the veil thins and you glimpse deeper reality. These aren't fantasies; they're the most real moments of your life.\n\nBring heaven down to earth. Live your spiritual vision in practical, grounded ways that serve both your growth and the awakening of others.` },
  22: { title: "The Visionary Heart", keywords: ["Grand Purpose", "World-building", "Legacy"], shortDesc: "Your soul is driven to build something of monumental, world-changing significance.", fullText: `Small thinking suffocates your soul. You need goals that challenge the very limits of what's possible — and you possess the inner resources to achieve them. You feel most alive working on large-scale projects matching the enormity of your vision.\n\nPace yourself. Build systematically. Trust that the universe gave you both the vision and the capacity to manifest it — one solid step at a time.` },
  33: { title: "The Healer's Heart", keywords: ["Unconditional Love", "Healing", "Sacrifice"], shortDesc: "Your soul yearns to love unconditionally and heal at the most profound level.", fullText: `Your drive toward unconditional love and selfless service transcends ordinary human experience. You feel most fulfilled serving others at the deepest level — with pure compassion that transforms pain into purpose.\n\nMaintain purity of intention while establishing boundaries that prevent being consumed by others' needs. The world needs your healing presence, but only if you remain whole enough to offer it.` },
};

export const personalityInterpretations: Record<number, NumberInterpretation> = {
  1: { title: "The Commanding Presence", keywords: ["Strong", "Confident", "Direct"], shortDesc: "Others perceive you as a natural leader with confidence and the assertiveness to make things happen.", fullText: `You project an aura of confidence and self-assurance that commands immediate attention. People perceive you as someone who knows what they want and isn't afraid to pursue it. Your energy communicates "I can handle this."\n\nBe aware this can create distance — people may assume you don't need help or support. Showing vulnerability selectively deepens connections without sacrificing respect.` },
  2: { title: "The Gentle Presence", keywords: ["Approachable", "Warm", "Tactful"], shortDesc: "Others see you as warm, approachable, and naturally diplomatic — putting everyone at ease.", fullText: `People perceive you as someone who genuinely listens and cares about their feelings. You radiate quiet grace that puts others at ease. Your outward energy says "I'm here for you" — drawing people to confide in you quickly.\n\nSome may mistake softness for weakness. Displaying your inner steel occasionally reminds others that kindness and strength aren't mutually exclusive.` },
  3: { title: "The Charismatic Presence", keywords: ["Charming", "Expressive", "Entertaining"], shortDesc: "The world sees you as charismatic and entertaining — someone whose charm lights up every room.", fullText: `When you enter a room, people notice. Not because you're loud, but because your natural charisma creates a gravitational pull. Others see you as witty, creative, and genuinely fun to be around. You dress with flair and express yourself with natural dramatic timing.\n\nOthers may not always take you seriously. When you need to convey depth, consciously modulating your expressiveness helps them see the substance beneath the sparkle.` },
  4: { title: "The Reliable Presence", keywords: ["Dependable", "Practical", "Organized"], shortDesc: "Others perceive you as solid and dependable — someone who can be trusted completely.", fullText: `People perceive you as someone who has their life together and whose word is as solid as bedrock. You radiate stability. Your appearance communicates professional respect and methodical competence.\n\nOthers may see you as rigid or overly serious. Occasionally showing your lighter, more spontaneous side prevents typecasting as all work and no play.` },
  5: { title: "The Magnetic Presence", keywords: ["Dynamic", "Exciting", "Versatile"], shortDesc: "The world sees you as dynamic and irresistibly magnetic — bringing energy wherever you go.", fullText: `People perceive you as someone who lives life at full volume — adventurous, daring, impossible to ignore. Your energy communicates freedom and delicious unpredictability. Your body language is open and invites adventure.\n\nSome may wonder if your exciting exterior masks lack of depth. Demonstrating follow-through on important matters helps others trust your substance as much as they enjoy your sparkle.` },
  6: { title: "The Nurturing Presence", keywords: ["Caring", "Responsible", "Beautiful"], shortDesc: "Others see you as caring and aesthetically refined — creating beauty and warmth wherever you go.", fullText: `People perceive you as someone who genuinely cares about others' wellbeing with a natural eye for beauty. You radiate domestic grace and emotional availability. Others instinctively trust you with their hearts.\n\nOthers may take your caretaking for granted. Setting clear boundaries while maintaining warmth teaches others to reciprocate the care you so generously offer.` },
  7: { title: "The Mysterious Presence", keywords: ["Enigmatic", "Intelligent", "Reserved"], shortDesc: "Others perceive you as intriguingly mysterious — an intellectual with hidden depths worth discovering.", fullText: `You project an aura of quiet intelligence and self-contained mystery. People sense depth in you and are intrigued by what lies beneath your composed exterior. Your energy says "there's much more here than meets the eye."\n\nThis reserve can be misread as coldness or arrogance. Offering small windows into your inner world rewards those who take the time to know you and prevents isolation.` },
  8: { title: "The Powerful Presence", keywords: ["Authoritative", "Successful", "Commanding"], shortDesc: "Others see you as powerful, successful, and naturally authoritative — someone who gets things done.", fullText: `You project an image of competence, authority, and material success. People perceive you as a natural boss — someone who can handle complex situations and make tough decisions without flinching. Your presence communicates "I mean business."\n\nThis can intimidate people who might otherwise become allies. Balancing your powerful exterior with moments of warmth and accessibility creates loyal relationships that amplify your influence.` },
  9: { title: "The Worldly Presence", keywords: ["Sophisticated", "Compassionate", "Refined"], shortDesc: "The world sees you as wise, compassionate, and sophisticated — someone with a universal quality.", fullText: `People perceive you as someone who has seen and understood much of life. You project a quality of worldly wisdom, tolerance, and refinement that makes you seem approachable regardless of background. Your energy communicates universal acceptance.\n\nOthers may place you on a pedestal, expecting perfection. Showing your human side — including struggles and imperfections — creates more authentic connections.` },
  11: { title: "The Luminous Presence", keywords: ["Inspiring", "Ethereal", "Magnetic"], shortDesc: "Others sense something otherworldly about you — an inspiring, almost ethereal quality they can't quite name.", fullText: `People perceive an unusual quality in you — something luminous and slightly otherworldly that they can't quite articulate. You project spiritual depth and inspirational energy that can move others deeply, sometimes without saying a word.\n\nThis ethereal quality can make practical interactions challenging. Grounding your spiritual magnetism in relatable, down-to-earth behavior helps others connect with you as a person, not just a presence.` },
  22: { title: "The Visionary Leader", keywords: ["Commanding", "Inspiring", "Formidable"], shortDesc: "Others perceive you as a formidable visionary — someone capable of achieving the seemingly impossible.", fullText: `People perceive you as someone operating on a level that few can match. Your presence communicates both grand vision and practical capability — a rare combination that inspires confidence in even the most ambitious undertakings.\n\nThis perception can create isolation if others feel they can't relate to your intensity. Making your grand vision accessible through storytelling and genuine connection builds the teams you need to manifest your vision.` },
  33: { title: "The Radiant Healer", keywords: ["Loving", "Wise", "Transcendent"], shortDesc: "Others experience you as a radiant, healing presence — someone whose very being uplifts those around them.", fullText: `People perceive something extraordinary in your presence — a quality of unconditional love and healing wisdom that seems to transcend ordinary human interaction. Others feel better simply by being near you.\n\nThis perception can attract those who want to be healed without doing their own work. Maintaining loving boundaries ensures your energy serves those genuinely ready for transformation.` },
};

export const personalYearInterpretations: Record<number, NumberInterpretation> = {
  1: { title: "Year of New Beginnings", keywords: ["Fresh Start", "Initiative", "Independence"], shortDesc: "This year marks a powerful new cycle — plant bold seeds for the next nine years of your life.", fullText: `This is your reset year — the start of a brand-new nine-year cycle. The energy of 1 demands that you take initiative, make bold decisions, and start projects that align with your authentic vision. What you plant now determines what you'll harvest for years to come.\n\nDon't wait for permission or perfect conditions. The universe is literally opening doors for you — but only you can walk through them. Be courageous. Be original. This year rewards action over analysis.` },
  2: { title: "Year of Partnership", keywords: ["Patience", "Cooperation", "Relationships"], shortDesc: "A year for deepening connections, practicing patience, and letting things unfold naturally.", fullText: `After last year's bold energy, this year asks you to slow down and focus on relationships, cooperation, and the subtle art of patience. Seeds planted in your 1 year need time to develop — resist the urge to force growth.\n\nPay attention to partnerships — both personal and professional. The right collaborations formed now will prove invaluable. Trust the process. What feels like delay is actually divine timing.` },
  3: { title: "Year of Expression", keywords: ["Creativity", "Social Life", "Joy"], shortDesc: "A vibrant year for creative expression, social expansion, and rediscovering joy.", fullText: `This year the universe invites you to play, create, and express yourself with abandon. Your creativity is amplified, your social magnetism is heightened, and opportunities for joy multiply. Say yes to invitations, start creative projects, and let your personality shine.\n\nThe risk this year is scattering your energy too thin. Channel your creative enthusiasm into focused projects that showcase your talents rather than dabbling in everything that catches your eye.` },
  4: { title: "Year of Foundation", keywords: ["Hard Work", "Structure", "Discipline"], shortDesc: "A year for serious building — laying foundations that will support your dreams for years to come.", fullText: `This is your year to build, organize, and create solid foundations. The universe rewards hard work and discipline now, asking you to put in the effort that transforms dreams into structures. Health, finances, career systems — attend to the practical architecture of your life.\n\nIt may feel demanding, but every hour of effort invested now pays compound dividends. Don't cut corners. The foundations you lay this year determine how high you can eventually build.` },
  5: { title: "Year of Freedom", keywords: ["Change", "Adventure", "Liberation"], shortDesc: "A year of exciting change, unexpected opportunities, and liberating breakthroughs.", fullText: `Expect the unexpected. This year brings dynamic change, travel opportunities, and the chance to break free from restrictions that have held you back. The energy is electric and fast-moving — adaptability is your greatest asset.\n\nEmbrace change rather than resisting it. The disruptions that seem chaotic now are actually liberating you from structures that no longer serve your growth. Stay flexible, say yes to adventure, and trust the ride.` },
  6: { title: "Year of Responsibility", keywords: ["Family", "Home", "Service"], shortDesc: "A year focused on home, family, love, and stepping into greater responsibility.", fullText: `This year centers on domestic life, relationships, and the responsibilities that come with love. Family matters take priority — you may move, renovate, marry, or deepen commitments. The universe asks you to nurture and be nurtured.\n\nThe lesson: responsibility chosen with love is not a burden but a privilege. Create beauty in your home, strengthen your closest relationships, and attend to the wellbeing of your community.` },
  7: { title: "Year of Inner Growth", keywords: ["Reflection", "Wisdom", "Solitude"], shortDesc: "A year for going inward — deep reflection, spiritual growth, and gaining profound wisdom.", fullText: `This year, the universe asks you to slow down, go inward, and seek deeper understanding. It's a year for study, meditation, analysis, and spiritual development. Solitude isn't loneliness now — it's the crucible where wisdom forms.\n\nDon't force external achievements. The growth happening is internal and invisible, but it's the most important work you'll do. Trust the quiet. What you discover within yourself this year will guide your decisions for the rest of the cycle.` },
  8: { title: "Year of Abundance", keywords: ["Achievement", "Power", "Reward"], shortDesc: "A year of harvesting rewards, stepping into power, and achieving material success.", fullText: `This is your power year — a time when effort meets opportunity and the universe rewards your accumulated work. Financial gains, career advancement, and recognition are all heightened now. Step confidently into positions of greater authority.\n\nThe energy demands that you think big and act decisively. Negotiations, investments, and business decisions made now carry extra weight. Align your material pursuits with your values and watch abundance multiply.` },
  9: { title: "Year of Completion", keywords: ["Release", "Transformation", "Endings"], shortDesc: "A year of powerful endings, release, and clearing space for the new cycle ahead.", fullText: `This is your completion year — the end of a nine-year cycle. The energy demands that you release what no longer serves you: relationships, habits, beliefs, possessions. Letting go feels difficult but is absolutely necessary. What you cling to now will become deadweight in your next cycle.\n\nThis isn't a year for starting new things — it's for finishing, forgiving, and clearing space. Practice gratitude for the cycle that's ending while making peace with its lessons. The fresh start of a 1 year awaits.` },
  11: { title: "Year of Illumination", keywords: ["Spiritual Awakening", "Intuition", "Inspiration"], shortDesc: "A rare, spiritually charged year — heightened intuition and potential for profound awakening.", fullText: `This Master Number year brings extraordinary spiritual intensity. Your intuition is razor-sharp, synchronicities multiply, and you may experience insights that fundamentally shift your understanding of reality. Pay attention to dreams, signs, and the quiet voice of inner knowing.\n\nThe intensity can be overwhelming. Ground yourself through meditation, nature, and creative expression. Channel the heightened energy into inspired projects rather than letting it scatter into anxiety.` },
  22: { title: "Year of Manifestation", keywords: ["Building", "Legacy", "Grand Vision"], shortDesc: "A rare Master Builder year — your capacity to manifest grand visions into reality is at its peak.", fullText: `This is one of the most powerful years possible in numerology. Your ability to envision and execute large-scale projects is dramatically amplified. Think in terms of legacy — what you build now has the potential to endure and serve for years or even generations.\n\nDon't waste this energy on small objectives. Aim high, plan thoroughly, and trust your ability to achieve what others consider impossible. The universe is quite literally conspiring to support your grandest vision.` },
  33: { title: "Year of Service", keywords: ["Healing", "Teaching", "Unconditional Love"], shortDesc: "The rarest year vibration — a calling to serve, heal, and teach through unconditional love.", fullText: `This extraordinarily rare vibration calls you into your highest potential as a healer and teacher. Your capacity for compassion is amplified to its maximum, and the universe presents opportunities to serve in ways that create profound transformation.\n\nThe key is maintaining your own wellbeing while serving others. This year tests your ability to love unconditionally while keeping boundaries that prevent burnout. Master this balance, and your impact will be remarkable.` },
};

export const birthdayInterpretations: Record<number, string> = {
  1: "Born on the 1st: You carry the gift of original leadership. Your special talent is the ability to initiate — to see what needs to exist and bring it into being through sheer will and creativity.",
  2: "Born on the 2nd: You carry the gift of intuitive diplomacy. Your special talent is reading the unspoken — sensing what others need before they know it themselves.",
  3: "Born on the 3rd: You carry the gift of joyful expression. Your special talent is the ability to transform any idea into something that moves, inspires, or delights others.",
  4: "Born on the 4th: You carry the gift of practical mastery. Your special talent is turning chaos into order and dreams into tangible, lasting structures.",
  5: "Born on the 5th: You carry the gift of dynamic adaptability. Your special talent is thriving in change — seeing opportunity where others see only disruption.",
  6: "Born on the 6th: You carry the gift of nurturing wisdom. Your special talent is creating environments where people feel safe enough to heal and grow.",
  7: "Born on the 7th: You carry the gift of penetrating insight. Your special talent is seeing through surface appearances to the hidden truth beneath.",
  8: "Born on the 8th: You carry the gift of material manifestation. Your special talent is understanding the flow of resources and directing them toward meaningful achievement.",
  9: "Born on the 9th: You carry the gift of universal compassion. Your special talent is the ability to see the best in people and inspire them toward their highest potential.",
  10: "Born on the 10th: You carry the amplified gift of the pioneer with added sensitivity. Your leadership is both visionary and deeply attuned to others' needs.",
  11: "Born on the 11th: You carry the Master Number gift of spiritual illumination. Your special talent is channeling inspired ideas that can shift collective consciousness.",
  12: "Born on the 12th: You carry the gift of creative communication. Your special talent is synthesizing complex ideas into forms that are both beautiful and universally accessible.",
  13: "Born on the 13th: You carry the gift of transformative building. Your special talent is taking what's broken and rebuilding it stronger — turning obstacles into cornerstones.",
  14: "Born on the 14th: You carry the gift of grounded freedom. Your special talent is finding adventure and growth within structure — freedom through mastery rather than escape.",
  15: "Born on the 15th: You carry the gift of magnetic nurturing. Your special talent is combining personal magnetism with genuine care, creating devoted followings wherever you go.",
  16: "Born on the 16th: You carry the gift of spiritual depth. Your special talent is accessing profound inner wisdom through periods of solitude and introspection.",
  17: "Born on the 17th: You carry the gift of spiritual authority. Your special talent is wielding influence with integrity, achieving success that aligns with higher purpose.",
  18: "Born on the 18th: You carry the gift of powerful compassion. Your special talent is combining material strength with humanitarian vision to create meaningful change.",
  19: "Born on the 19th: You carry the gift of independent wisdom. Your special talent is pioneering new paths while carrying the accumulated wisdom of past experiences.",
  20: "Born on the 20th: You carry the gift of heightened sensitivity. Your special talent is perceiving the subtle currents of emotion and energy that shape every interaction.",
  21: "Born on the 21st: You carry the gift of creative charm. Your special talent is communicating with such warmth and creativity that you naturally attract opportunities.",
  22: "Born on the 22nd: You carry the Master Builder gift. Your special talent is envisioning grand possibilities and possessing the practical genius to make them real.",
  23: "Born on the 23rd: You carry the gift of versatile communication. Your special talent is adapting your message to any audience while maintaining authenticity and spark.",
  24: "Born on the 24th: You carry the gift of devoted service. Your special talent is combining practical skills with genuine love to create lasting value for others.",
  25: "Born on the 25th: You carry the gift of intuitive analysis. Your special talent is combining sharp intellect with deep intuition to reach insights others cannot access.",
  26: "Born on the 26th: You carry the gift of responsible power. Your special talent is managing resources and people with both authority and genuine care for their wellbeing.",
  27: "Born on the 27th: You carry the gift of compassionate leadership. Your special talent is leading through inspiration and universal understanding rather than force.",
  28: "Born on the 28th: You carry the gift of independent partnership. Your special talent is maintaining strong individuality while building powerful collaborative relationships.",
  29: "Born on the 29th: You carry the gift of visionary sensitivity. Your special talent is receiving inspired visions and translating them into practical guidance for others.",
  30: "Born on the 30th: You carry the gift of amplified expression. Your special talent is communicating with such power and creativity that your words leave lasting impressions.",
  31: "Born on the 31st: You carry the gift of creative discipline. Your special talent is combining artistic vision with methodical execution — imagination grounded in reality.",
};

export function getInterpretation(type: string, number: number): NumberInterpretation | undefined {
  switch (type) {
    case "lifePath": return lifePathInterpretations[number];
    case "expression": return expressionInterpretations[number];
    case "soulUrge": return soulUrgeInterpretations[number];
    case "personality": return personalityInterpretations[number];
    case "personalYear": return personalYearInterpretations[number];
    default: return undefined;
  }
}
